Handle pypi data source fetch
chanzuckerberg/napari-hub pull request #1062
Opened 2023-05-18 06:49 UTC by manasaV3

## Description

## Demos

2023-05-24 19:01 UTC, aganders3 requested changes
Sorry for the number of comments - as mentioned many of these things are nitpicks. Overall this code is very readable and makes sense to me! There are a few things I would like to see changed as I think they could hide errors down the line in both testing and usage (for example the mutable fixtures, `MockResponse`, and `get_attribute`).

2023-05-25 14:13 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/models/plugin_metadata_type.py
> +        return f"{version}:{self.name}"
I don't think this implementation is correct - the resulting enum only has the `PYPI` member and the others are kind of like aliases for it.

```python
>>> PluginType.PYPI.name
'PYPI'
>>> PluginType.SOURCE_CONTROL.name
'PYPI'
```

Maybe you want to use `auto` to set the member values:
```
from enum import auto
class PluginType(Enum):
     PYPI = auto()
     SOURCE_CONTROL = auto()
     DISTRIBUTION = auto()
```

2023-05-30 13:24 UTC, aganders3 commented on data-workflows/plugin/processor.py
> +    put_pypi_record(plugin=plugin_name, version=version, is_latest=True)
Sorry I think I'm just missing some of the context here. My initial comment was about this being is a 1-line function, and the inner function itself (`put_pypi_record`) is used directly in the code right below where this gets called. If the function will grow I think it makes sense, but then to be consistent I might suggest abstracting both calls in the code above.

Re: `pass` I would reserve it for where necessary and instead put a `# TODO` or something here.

2023-05-30 13:25 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/_tests/models/test_plugin.py
> +    def _put_item(cls, table, name, version, is_latest):
My thoughts on this are just that I prefer not to take the `cls` parameter if it is not used. I think it makes it more clear by reading the signature what you can expect in the method.

2023-06-14 21:41 UTC, manasaV3 commented
Changes from this PR have been merged into the main as a part of https://github.com/chanzuckerberg/napari-hub/pull/1108

2023-06-14 21:41 UTC, closed without merging