clarify sort labels
chanzuckerberg/napari-hub pull request #108
Opened 2021-06-25 15:40 UTC by kne42

First release -> Created
Release date -> Last updated

([relevant issue](https://airtable.com/tblNxANme1LbVQqq1/viwISga6FERUatih1/recd9jyNu4zagTzvf?blocks=hide))

2021-06-25 20:14 UTC, codemonkey800 approved these changes
LGTM! 🌮

2021-06-25 20:29 UTC, neuromusic requested changes
the airtable notes included a request for different wording for the search filters:

> sort by "Recently updated" and "Newest".

also, can you confirm that this PR fixes the sort order to reflect that the top results are the most recently updated and newest for each of the selections?

2021-06-25 20:29 UTC, neuromusic commented on client/src/components/PluginSearch/PluginSortByForm.tsx
> +  [SearchSortType.FirstReleased]: 'Created',
```suggestion
  [SearchSortType.FirstReleased]: 'Newest',
```

2021-06-25 20:29 UTC, neuromusic commented on client/src/components/PluginSearch/PluginSortByForm.tsx
> +  [SearchSortType.ReleaseDate]: 'Last updated',
```suggestion
  [SearchSortType.ReleaseDate]: 'Recently updated',
```

2021-06-25 20:31 UTC, neuromusic commented on client/src/components/PluginSearch/PluginSortByForm.tsx
> +  [SearchSortType.FirstReleased]: 'Created',
b/c "Newest" makes it clear what the sort order is

2021-06-25 20:48 UTC, codemonkey800 commented
> also, can you confirm that this PR fixes the sort order to reflect that the top results are the most recently updated and newest for each of the selections?

ah i forgot about this (although the airtable didn't say anything about it 🤔 ). @kne42 the implementations for the sorters are here:
https://github.com/chanzuckerberg/napari-hub/blob/912f18b1979911315521c3ad298ea4cc1fca84e2/client/src/context/search/sorters.ts#L17-L37

2021-06-25 22:49 UTC, neuromusic commented
>the airtable didn't say anything about it

sorry, I thought it was implied w/ the "Recently updated" and "Newest" labels

2021-06-28 18:51 UTC, kne42 commented
@neuromusic Ah, apologies, it seems that the notes are hidden for me by default. Could you clarify how exactly the functionality needs to change? Also it wasn't clear to me that anything more than the text needed to change since it's labeled as a "Copy" issue.

2021-06-28 19:25 UTC, codemonkey800 commented
> @neuromusic Ah, apologies, it seems that the notes are hidden for me by default. Could you clarify how exactly the functionality needs to change? Also it wasn't clear to me that anything more than the text needed to change since it's labeled as a "Copy" issue.

that's what I was thinking too, is there a separate issue regarding the sort? maybe we can have that implemented in a separate PR 🤔

2021-06-28 21:41 UTC, neuromusic commented
I'll let you two decide if you want to land the changes in one PR or two, but the functionality should be...

- sort by "Release date" becomes sort by "Recently updated". sorts by "release date" metadata, from high to low (newest to oldest)
- sort by "First release" becomes sort by "Newest". sorts by "First release" metadata, from high to low (newest to oldest)

2021-06-28 21:55 UTC, kne42 commented
Ok, thanks for the clarifications @neuromusic! I think this change is simple enough that I can add it on to this PR. I'll include some tests as well to verify that things behave as we expect.

2021-06-28 23:09 UTC, kne42 commented
Ok, I've added tests that verify the search results are being ordered from newest to oldest. You can take a look at the tests I wrote to double check that this is the behavior we expect.

2021-06-28 23:40 UTC, codemonkey800 commented on client/src/context/search/sorters.test.ts
> +}
nit: this is a really cool implementation, but I would prefer if we use `lodash` functions whenever possible. It looks like there's a [shuffle()](https://lodash.com/docs/4.17.15#shuffle) function that does the same thing.

2021-06-28 23:40 UTC, codemonkey800 commented on client/src/context/search/sorters.ts
> +export function compareDates(dateA: string, dateB: string): number {
This is intentionally an internal function used primarily by the sorters (which are also internal functions). Generally I've been testing the things that are actually exported (aka the public API). In this case, the only export for this module is `sortResults()`, so I expect the tests in `sorters.test.ts` to test that function.

I prefer testing only publicly exported functions, but I realize it's a pretty polarizing topic:
- https://philipwalton.com/articles/why-i-test-private-functions-in-javascript/
- https://kentcdodds.com/blog/testing-implementation-details
- https://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones

Ultimately, I'll leave the decision up to you on how you want test this, but it would be nice to have tests for the `sortResults()` plugin.

2021-06-28 23:40 UTC, codemonkey800 commented on client/src/context/search/sorters.ts
>    return new Date(dateA).getTime() - new Date(dateB).getTime();
You might need to reverse this calculation? I checked out your branch and I see the older dates still showing up on the top:

![image](https://user-images.githubusercontent.com/2176050/123716388-51100900-d82f-11eb-881d-773b0dac3d8b.png)

2021-06-29 21:08 UTC, kne42 commented
@codemonkey800 and i agreed to add more tests for each sort function later, but it seems to be working now

2021-06-29 21:10 UTC, codemonkey800 commented on client/src/context/search/sorters.ts
> +export function compareDates(dateA: string, dateB: string): number {
For everyone else's context, we agreed to leave the test for the internal implementation and to add tests for `sortResults()` in the future

2021-06-29 21:10 UTC, codemonkey800 approved these changes

2021-06-29 22:10 UTC, neuromusic approved these changes
LGTM

2021-06-30 03:33 UTC, merged