Creating plugin aggregation workflow
chanzuckerberg/napari-hub pull request #1109
Opened 2023-06-15 21:26 UTC by manasaV3

## Description

## Demos

2023-06-23 15:57 UTC, aganders3 requested changes
This generally looks good to me on quick review, but I can't seem to get the tests to run. Did you update `nhcommons` to be Python 3.9+?

Even if I create a new env with 3.9 I get some errors:
```
FAILED src/nhcommons/tests/models/test_plugin.py::TestPlugin::test_get_latest_plugins[data0-expected0] - AssertionError: assert {'bar': '0.8.1'} == {}
FAILED src/nhcommons/tests/models/test_plugin.py::TestPlugin::test_get_latest_plugins[data1-expected1] - AssertionError: assert {'bar': '0.8.... 'foo': '1.1'} == {'baz': '0.0.3', 'foo': '1.1'}
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query_invalid_values[None-None] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query_invalid_values[-None] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query_invalid_values[None-] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query_invalid_values[-] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-1-0.0.1-plugin_1_0_0_1] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-2-0.0.1-plugin_2_0_0_1] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-3-0.0.1-plugin_3_0_0_1] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-1-0.0.2-plugin_1_0_0_2] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-2-0.0.2-plugin_2_0_0_2] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-3-0.0.2-plugin_3_0_0_2] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
FAILED src/nhcommons/tests/models/test_plugin_metadata.py::TestPluginMetadata::test_query[plugin-2-0.0.3-plugin_2_0_0_3] - AttributeError: module 'nhcommons.models.plugin_metadata' has no attribute 'query_for_plugin_version'
```

My inline comments/suggestions work to get these tests passing, so otherwise the PR seems okay to me :)

2023-06-23 15:57 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/tests/models/test_plugin_metadata.py
> +        assert plugin_metadata.query_for_plugin_version(plugin, version) == []
```suggestion
        assert plugin_metadata.query(plugin, version) == []
```

2023-06-23 15:57 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/tests/models/test_plugin_metadata.py
> +        actual = plugin_metadata.query_for_plugin_version(plugin, version)
```suggestion
        actual = plugin_metadata.query(plugin, version)
```

2023-06-23 15:57 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/models/plugin.py
> +    is_latest = UnicodeAttribute(null=True)
```suggestion
    is_latest = BooleanAttribute(null=True)
```

2023-06-23 15:57 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/models/plugin.py
> +    ListAttribute,
```suggestion
    ListAttribute,
    BooleanAttribute,
```

2023-06-23 15:57 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/models/plugin.py
>  class _LatestPluginIndex(GlobalSecondaryIndex):
I think `is_latest` maybe needs to be added back here as well? These changes make the tests pass, but I'm not sure if they're correct as I know almost nothing about DynamoDB.

2023-06-26 20:35 UTC, manasaV3 commented on napari-hub-commons/src/nhcommons/tests/models/test_plugin_metadata.py
> +        assert plugin_metadata.query_for_plugin_version(plugin, version) == []
Not sure how the refactor missed the test. 😱

2023-06-26 20:38 UTC, manasaV3 commented on napari-hub-commons/src/nhcommons/models/plugin.py
> +    is_latest = UnicodeAttribute(null=True)
This is a unicode property because of an issue with terraform. Terraform only doesn't allows attributes that are range and hash keys to be boolean. 😞

2023-06-26 20:45 UTC, aganders3 commented on napari-hub-commons/src/nhcommons/models/plugin.py
> +    is_latest = UnicodeAttribute(null=True)
Haha okay I will take your word for it on that. `src/nhcommons/tests/models/test_plugin.py` still fails though unless I revert the changes to the `_LatestPluginIndex` (adding `is_latest` back there with `range_key=True`).

2023-06-27 18:34 UTC, manasaV3 commented on napari-hub-commons/src/nhcommons/models/plugin.py
>  class _LatestPluginIndex(GlobalSecondaryIndex):
Yup, it is needed here for these tests as it needs to understand what the dynamo index schema looks like. In the real use case, that wasn't needed, as the schema was defined in terraform.

2023-06-27 20:01 UTC, aganders3 approved these changes
Thanks for taking the time to explain all that to me today!

I pushed https://github.com/chanzuckerberg/napari-hub/pull/1109/commits/0222acf2e880001fd34057ba2febaed02419ef7a to fix the typing issues I was having, and now tests pass for me in both 3.8 and 3.9 envs.

2023-06-29 21:05 UTC, merged