add v0 tech spec
chanzuckerberg/napari-hub pull request #197
Opened 2021-07-09 18:59 UTC by ziyangczi

Added v0 tech spec after clean up

2021-07-10 00:40 UTC, justinelarsen requested changes
Thanks for this PR @ziyangczi ! Overall, it looks good. I suggested a bunch of edits.

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +  * Setup health check for the http server
```suggestion
  * Health check for the http server
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +First version of the site will be released on production by June 30, 2021.
```suggestion
First version of the site was released on production on June 30, 2021. Subsequent major and minor versions to follow.
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +Need to work with infra team to purchase domain or use subdomain subpage of napari.org.
```suggestion
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +Solutions
```suggestion

### Solutions
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +bigquery dataset as a backup data source when the main query fails (this should also triggers an alert to our team
```suggestion
bigquery dataset as a backup data source when the main query fails (this should also trigger an alert to our team 
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +alerts and make adjustment (be it pypi outage or pypi website structure change  to address the failure and bring the
```suggestion
alerts and make adjustment (be it pypi outage or pypi website structure change to address the failure and bring the
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +“[“plugin_1”, “plugin_2]”, where each individual plugin name can then be used to query qypi api
```suggestion
“[“plugin_1”, “plugin_2]”, where each individual plugin name can then be used to query pypi API.
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +  * return list of plugin and versions:
```suggestion
  * return list of plugin and versions
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +We decided to use AWS which we will use services like Lambda, S3 and API Gateway.
```suggestion
We decided to use AWS which we will use services like Lambda, S3 and API Gateway. A software architecture diagram can be found [here](https://lucid.app/lucidchart/1ad7e89e-7265-4a04-b37b-135e7a57432c/view).
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +information to support this decision can be found in this document:Next.js vs SvelteKit
We may want to publish a summary of the findings. If we're not right now, let's remove this line.

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +    document Material UI Integration
Same as above, if we're not going to publish the findings, let's remove this line.

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +* Who is responsible for the maintenance of this site?
```suggestion
For feature requests, please file [a new discussion under the ideas category](https://github.com/chanzuckerberg/napari-hub/discussions/categories/ideas).
For bug reports, please file [a new issue](https://github.com/chanzuckerberg/napari-hub/issues).
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +## Success Evaluation
```suggestion
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +Achieve OKR “At least 25 plugins discoverable through a plugin discovery site” by end of H1 2021
```suggestion
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +## Questions
Please remove this entire section.

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +    * Link to details page
```suggestion
    * Link to details page
    * We will add an “exclude” list for plugins to exclude from the list. The exclusions will be stored in a file and plugin data returned will not include those excluded plugins.
```

2021-07-10 00:40 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +
```suggestion

## Publishing of plugins
* To be transparent and not require an approval process as well as share the responsibility to flagging bad plugins, we will publish activity to the hub-updates stream on the [napari Zulip](https://napari.zulipchat.com). Activity will be published for brand new plugins, new versions of plugins as well as plugin removals.

```

2021-07-12 20:38 UTC, codemonkey800 commented on docs/v0-tech-spec.md
> +* TBD Specifications on ordering, fuzzy search, etc. will be determined once Jeremy researches options in Solution #3.
Added! 🔥

2021-07-12 20:47 UTC, justinelarsen approved these changes
Looks great to me! Thanks for making all my suggested changes! 😄 🎉

2021-07-12 23:56 UTC, merged

2021-07-13 00:37 UTC, justinelarsen commented on docs/v0-tech-spec.md
> +* TBD Specifications on ordering, fuzzy search, etc. will be determined once Jeremy researches options in Solution #3.
Thank you! 😃