Render markdown on backend
chanzuckerberg/napari-hub pull request #205
Opened 2021-07-14 20:10 UTC by codemonkey800

## Description

This PR moves the description rendering functionality to the backend to [speed up initial load on the frontend](https://docs.google.com/document/d/1ykAnPTPLWf5Hxfisnlg8eehyTpb0xY9BHqaAQ5tFWeo/edit?usp=sharing). 

This works by rendering the Markdown to HTML, and then using an HTML parser to extract only the textual content from the HTML.

Moving rendering to the backend improves SSR response time from ~1203 millisecondsto ~608 milliseconds, a nearly 2x improvement.

## Demo

Without backend rendering: https://perf-main-frontend.dev.imaging.cziscience.com/
With backend rendering: https://speed-up-hub-frontend.dev.imaging.cziscience.com

2021-07-15 20:08 UTC, ziyangczi commented on backend/napari.py
> +    description_text = render_description(description)
maybe just include this in the extra metadata set

2021-07-15 20:46 UTC, codemonkey800 commented on backend/napari.py
> +    description_text = render_description(description)
I looked into it and I'm not sure if I can because `description` can come from the `extra_metadata` or `plugin.info`. Or did you want me to add it to the set after creating it?

```py
extra_metadata['description_text'] = render_description(description)
```

2021-07-15 21:54 UTC, ziyangczi requested changes
added suggestion to package description text

2021-07-15 21:54 UTC, ziyangczi commented on backend/napari.py
> +    description_text = render_description(description)
I meant: 
```suggestion
    extra_metadata['description_text'] = render_description(description)
```

2021-07-15 21:54 UTC, ziyangczi commented on backend/napari.py
> +        "description_text": description_text,
```suggestion
        "description_text": extra_metadata.get('description_text', ''),
```

2021-07-15 21:55 UTC, ziyangczi requested changes
would be nice to package the description text in extra metadata. sorry I can't make it one commit, I tried to add these change to a batch not not sure why they are now showing as a batch. but the idea is to add some clarity where these metadata is coming from

2021-07-15 21:56 UTC, ziyangczi commented on backend/napari.py
> +    description_text = render_description(description)
hmm somehow I can't batch these changes... but they should go in together

2021-07-15 21:58 UTC, ziyangczi commented on backend/napari.py
> +        "description_text": description_text,
so you can also undo the change above. though minor but this allows us to consistently see where everything is coming from

2021-07-15 22:01 UTC, ziyangczi commented on frontend/src/components/PluginSearch/PluginSearchResult.tsx
> +          {isSearching && matches.description_text && (
if we are not using the raw description anywhere in the frontend code, we should just drop description from the json, thoughts?

2021-07-15 22:03 UTC, ziyangczi commented
a general question, is there any identified difference between the beautifulsoup parsing solution to the current approach? particularly if anything bs4 can't handle/translate to HTML?

2021-07-15 23:42 UTC, codemonkey800 commented on frontend/src/components/PluginSearch/PluginSearchResult.tsx
> +          {isSearching && matches.description_text && (
Yeah we can remove from the `index_subset`, but we still need it for the plugin page 😅

2021-07-15 23:47 UTC, codemonkey800 commented
> a general question, is there any identified difference between the beautifulsoup parsing solution to the current approach? particularly if anything bs4 can't handle/translate to HTML?

BeautifulSoup is a full HTML parser, so I can't imagine there being a case where it can't handle HTML. The current approach actually could use BeautifulSoup to parse the pypi plugin page and query the data.

For my use case, the main benefit of using BeautifulSoup is the convenience of using `soup.get_text()` to get the textual content for the entire HTML document. If we wanted to parse for text using the current approach, we would need to write a lot of custom logic because we would need to recursively look at each HTML node and determine if it has text content.

2021-07-16 16:25 UTC, ziyangczi approved these changes

2021-07-19 18:18 UTC, merged