Add instructions for using napari hub shield to FAQ
chanzuckerberg/napari-hub pull request #262
Opened 2021-09-16 22:37 UTC by DragaDoncila

Add instructions for embedding shield into markdown (linking back to the hub) or just accessing the SVG.

Not sure if this is the best place to put this, but it made sense to me to put it under "Customizing your plugin's listing" - @neuromusic thoughts?

I'll also open a PR on the cookiecutter reop to add it to our README there, and once we release next week, advertise in the community meeting and on Zulip.

2021-09-16 22:51 UTC, neuromusic requested changes
Couple of changes, but otherwise LGTM!

2021-09-16 22:51 UTC, neuromusic commented on frontend/src/pages/faq.mdx
> +  title="How do I add a shield/badge for the hub to my repository?"
```suggestion
  title="How do I add a shield/badge for the napari hub to my repository?"
```

2021-09-16 22:51 UTC, neuromusic commented on frontend/src/pages/faq.mdx
> +you can copy paste this snippet:
```suggestion
you can copy & paste the snippet, replacing both instances of `<your-plugin-name-here>` with your plugin's package name:
```

2021-09-16 23:39 UTC, DragaDoncila commented
@neuromusic made those changes now (and fixed the tests)

2021-09-17 03:32 UTC, neuromusic approved these changes
🎉

2021-09-22 20:15 UTC, merged