Add category API
chanzuckerberg/napari-hub pull request #312
Opened 2021-11-07 02:19 UTC by potating-potato

Add API for category:
/category: get all category mappings
/category/<category>: match a particular category
/category/<category>/version/<version>: match a particular category under a specific version

Parse GitHub config for category metadata

Add category curation scripts to generate the mapping file from scratch.
Add curated mapping file for edam alpha06

2021-11-07 06:58 UTC, klai95 commented on backend/api/app.py
> +             and (rule.rule.startswith("/plugins")
`if all( ['GET' in rule.methods, rule.rule.startswith("/plugins"] ) 
  or any(rule.rule.startswith("/shields"), rule.rule.startswith("/category"))`

2021-11-07 07:15 UTC, klai95 commented on backend/api/model.py
> +                    "Image segmentation",
Does this mean that, in this case, `Image Segmentation` is the top-level parent, and `Manual Segmentation` is a leaf node?

2021-11-07 07:19 UTC, klai95 commented on backend/api/model.py
> +                         version="edam-alpha06") -> Union[Dict[str, List], List[Dict]]:
Is there a reason we have version set to `edam-alpha06' as a static value?

2021-11-07 07:21 UTC, klai95 commented on backend/api/model.py
> +    if not mappings:
Why is the `if not mappings` condition repeated here?

2021-11-07 07:21 UTC, klai95 commented on backend/api/model.py
> +    if not mappings:
Why is the `if not mappings` condition repeated here?

2021-11-07 07:27 UTC, klai95 commented on backend/category/edam.py
> +    Dict[str, List[str]]
Can you give a brief example of what Dict[str, List[str]] looks like for context?

2021-11-07 18:33 UTC, potating-potato commented on backend/api/model.py
> +                    "Image segmentation",
That is correct

2021-11-07 18:33 UTC, potating-potato commented on backend/api/model.py
> +                         version="edam-alpha06") -> Union[Dict[str, List], List[Dict]]:
the is currently the default version, we can remove it when we have more versions

2021-11-07 18:34 UTC, potating-potato commented on backend/api/model.py
> +    if not mappings:
when an invalid version is specified, the mapping returned would be None, in this scenario, we would return a static empty list

2021-11-07 18:35 UTC, potating-potato commented on backend/category/edam.py
> +    Dict[str, List[str]]
probably better to add as documentation here, will do

2021-11-07 20:55 UTC, klai95 approved these changes

2021-11-08 04:31 UTC, neuromusic requested changes
two concerns inline, otherwise looks great.

endpoints look 💯 . love the multi-hierarchy support. intuitive enough that they should serve (partially) as documentation for plugin devs

2021-11-08 04:31 UTC, neuromusic commented on backend/api/model.py
> +                         version="edam-alpha06") -> Union[Dict[str, List], List[Dict]]:
we should be more explicit here with our naming, as there are multiple EDAM ontologies, including "EDAM" (which is more broadly for the biosciences), EDAM Bioimaging (which we are using) and EDAM-geo (for geo & earth sciences which might be a candidate if we extend to other domains in the future).

`edam-bioimaging-alpha06` might be more appropriate

2021-11-08 04:31 UTC, neuromusic commented on backend/api/model.py
> +    if 'category' in metadata:
this schema doesn't match the one spec'd in the PRD, which lets the plugin dev specify the ontology:

```
labels:
  ontology: "EDAM-BIOIMAGING:alpha06"
  terms:
  - 3D Image                 # Data Shape
  - Cell segmentation        # Processing step
  - Model-based segmentation # Processing step
  - Fluorescence Microscopy  # Imaging Modality
```

2021-11-08 20:18 UTC, neuromusic approved these changes
my concerns have been addressed :D

2021-11-09 02:18 UTC, klai95 commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
What do you think of `github_metadata_parameters = ['project_site', 'documentation', 'support', 'report_issues', 'twitter']
project_urls_parameters = ['Project Site', 'Documentation', 'User Support', 'Report Issues', 'Twitter']
index_list = [i for i, project_url_parameter in enumerate(project_urls_parameters) if project_url_parameter in project_urls]
if len(index_list):
    github_metadata[github_metadata_parameters[index_list[0]]] = project_urls[project_urls_parameters[index_list[0]]]`?

2021-11-09 02:23 UTC, klai95 commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
What about 
![Screen Shot 2021-11-08 at 6 22 57 PM](https://user-images.githubusercontent.com/70177777/140850195-3256484b-8c71-4052-83b3-d80f20c7e4fe.png)?

2021-11-09 02:38 UTC, neuromusic commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
alternatively...

``` Python
mapping = {
    "Project Site": "project_site",
    "Documentation": "documentation",
    "User Support": "support",
    "Report Issues": "report_issues",
    "Twitter": "twitter",   
}

for param, url in project_urls.items():
    github_metadata[mapping[param]] = url
```

2021-11-09 02:47 UTC, klai95 commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
Does that mean in each instance of `project_urls`, `param` is the key and `url` is the value such that project_urls[param] == url?

2021-11-09 03:02 UTC, neuromusic commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
yeah, exactly

you can iterate over those key:value pairs in `project_urls` with `.items()`... this outputs a tuple of `(key,value)` which is assigned to `param` and `url`

2021-11-09 03:08 UTC, neuromusic commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
and by iterating over `project_urls`, the assignment only happens for project_urls which are defined... no need to check if the keys are present

although, now that I think of it, this will bork if there are stray keys in `project_urls` that aren't in `mapping`... in which case, could make `mapping` a defaultdict or add some try/except logic to the assignment in the for loop

2021-11-09 03:34 UTC, klai95 commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
Would this work?
``` Python
mapping = {
    "Project Site": "project_site",
    "Documentation": "documentation",
    "User Support": "support",
    "Report Issues": "report_issues",
    "Twitter": "twitter",   
}

for param, url in project_urls.items():
    if (param in mapping):
        github_metadata[mapping[param]] = url
```

2021-11-09 03:41 UTC, neuromusic commented on backend/utils/github.py
> +        if 'Project Site' in project_urls:
that would do it.

and good call re: defaultdict

2021-11-09 04:37 UTC, justinelarsen commented
Some high-level comments and questions:

1. Do we need both category and category_hierarchy on the plugin specific API? It seems like the category_hierarchy would be enough and the category is just redundant. https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/napari-demo
2. Should the plugin index API contain category info to build the search page listing? https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/index
3. Are these /category end points exposed for public use or are they just for internal consumption? I'm trying to understand why these are needed versus just adding the data returned to the existing /plugins end points. If they are necessary, I would rename "/category" to "/categories" to keep consistent with the "/plugins" API and because it's returning multiple.

2021-11-09 04:46 UTC, klai95 commented
> Some high-level comments and questions:
> 
> 1. Do we need both category and category_hierarchy on the plugin specific API? It seems like the category_hierarchy would be enough and the category is just redundant. https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/napari-demo
> 2. Should the plugin index API contain category info to build the search page listing? https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/index
> 3. Are these /category end points exposed for public use or are they just for internal consumption? I'm trying to understand why these are needed versus just adding the data returned to the existing /plugins end points. If they are necessary, I would rename "/category" to "/categories" to keep consistent with the "/plugins" API and because it's returning multiple.

That is a good call out to refactor `/category` to `/categories`. Would it make sense for `@app.route('/category/<category>/version/<version>')` to be refactored to `@app.route('/categories/<category>/versions/<version>')`?

2021-11-09 05:25 UTC, justinelarsen approved these changes

2021-11-09 05:25 UTC, justinelarsen commented on backend/api/model.py
> +        [
Thanks for adding return examples! It makes it a lot easier to visualize the real data.

2021-11-09 05:25 UTC, justinelarsen commented on backend/category/edam.py
> +        url = f'https://edamontology.org/EDAM-bioimaging_{version}.csv'
Consider using a constant and not repeating the URL for easier maintenance

2021-11-09 05:35 UTC, justinelarsen commented
> > Some high-level comments and questions:
> > 
> > 1. Do we need both category and category_hierarchy on the plugin specific API? It seems like the category_hierarchy would be enough and the category is just redundant. https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/napari-demo
> > 2. Should the plugin index API contain category info to build the search page listing? https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/index
> > 3. Are these /category end points exposed for public use or are they just for internal consumption? I'm trying to understand why these are needed versus just adding the data returned to the existing /plugins end points. If they are necessary, I would rename "/category" to "/categories" to keep consistent with the "/plugins" API and because it's returning multiple.
> 
> That is a good call out to refactor `/category` to `/categories`! Would it make sense for `@app.route('/category/<category>/version/<version>')` to be refactored to `@app.route('/categories/<category>/versions/<version>')`?

We should probably be consistent with "/versions" as well then to match the plugins end point.
Proposal would then be:
/category -> /categories
/category/<category> -> /categories/<category> 
/category/<category>/version/<version> -> /categories/<category>/versions/<version>

To match existing plugin end points:
/plugins
/plugins/<plugin>
/plugins/<plugin>/versions/<version>

2021-11-09 06:02 UTC, klai95 commented on backend/category/edam.py
> +        url = f'https://edamontology.org/EDAM-bioimaging_{version}.csv'
What about this approach? This approach essentially uses a ternary operator to yield the value to inject in %s, such that it is either an empty string or "_{version}". For example, if `version == "1.1"`, then `url = https://edamontology.org/EDAM-bioimaging_1.1.csv`. If `version == ""`, then `url = https://edamontology.org/EDAM-bioimaging.csv`

`url = "https://edamontology.org/EDAM-bioimaging%s.csv" % ("" if len(version) == 0 else f'_{version}')`

2021-11-09 09:49 UTC, klai95 commented on backend/api/model.py
> +    if not mappings:
Could you elaborate the logic of the series of `if` and `else` statements from `line 295` to `line 304`  for context?

2021-11-09 18:22 UTC, potating-potato commented
> 1. Do we need both category and category_hierarchy on the plugin specific API? It seems like the category_hierarchy would be enough and the category is just redundant. https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/napari-demo

The duplication is an attempt to make frontend easier by providing the exact data as required for the figma design. Yes we could drop the category and only use hierarchy, but frontend code would have to do one more level of querying when user tries to filter on the plugin. But if this is acceptable, I have no problem dropping the category (and/or rename the hierarchy)

> 2. Should the plugin index API contain category info to build the search page listing? https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/category-api/plugins/index

Yes it should, right now the napari-demo plugin is hidden so it does not show up in the search page, it would show up for other public plugins.

> 3. Are these /category end points exposed for public use or are they just for internal consumption? I'm trying to understand why these are needed versus just adding the data returned to the existing /plugins end points. If they are necessary, I would rename "/category" to "/categories" to keep consistent with the "/plugins" API and because it's returning multiple.

These endpoints would be public so that people can look at our internal mappings and query how ontology terms can be mapped to hub terms. The preview page serves some of the purpose, but this gives a more proactive approach to see how category works

2021-11-09 18:25 UTC, potating-potato commented on backend/api/model.py
> +    if not mappings:
I think this method may have been overloaded too much in logic, I can change this

2021-11-09 19:54 UTC, merged