Add documentation for setting up plugin preview
chanzuckerberg/napari-hub pull request #318
Opened 2021-11-12 01:00 UTC by DragaDoncila

This PR adds a document detailing the steps for setting up our plugin preview service.

**Outstanding questions:**
- Where do we direct the users for more info (if anywhere)? Pinging @neuromusic for info
- Does the explanation of how the plugin page is built need more detail, and is the current detail correct? Pinging @potating-potato and @codemonkey800 on that one
- @potating-potato I think at one stage you said the required workflow yml file is stored somewhere but I couldn't find it. I've pasted the relevant yml into the docs, but we may want to provide a download link for a file instead

**Still to do:**
- Update [GitHub action](https://github.com/chanzuckerberg/napari-hub-preview-action) README.md to point to this document
- Update [GtiHub app](https://github.com/apps/napari-hub-plugin-preview) page to point to this document
- Update hub FAQs "Can I preview my plugin listing" text
- Update napari.org "Creating plugin" page to point to this doc

I'll wait until we reach some sort of consensus on this doc before updating the remaining pages and cross-references.

2021-11-12 01:00 UTC, DragaDoncila commented on docs/setting-up-preview.md
> +First, you will need to install the napari Hub Plugin Preview GitHub app to the account or
we need to figure out what's going on with forks before we finalize the instructions for where to install the app

2021-11-12 02:35 UTC, potating-potato commented on docs/setting-up-preview.md
> +organization where the plugin lives.
the app can be added to the repo, instead of at account/organization level. But can be done at higher level for convenience if desired

2021-11-12 02:44 UTC, potating-potato reviewed
In general LGTM, had some suggestions.

Thanks for putting this together!

2021-11-12 02:44 UTC, potating-potato commented on docs/setting-up-preview.md
> +<!-- TODO: is 5 minutes accurate? -->
after the action is finished, there is a minimal gap before the comment is posted (a few seconds), would be easier to use the github action as the indicator

2021-11-12 02:44 UTC, potating-potato commented on docs/setting-up-preview.md
> +<!-- TODO: is this all valid and do we need more detail? -->
this is all correct

2021-11-12 02:44 UTC, potating-potato commented on docs/setting-up-preview.md
> +<!-- TODO: what do we want the user to do if they want more information -->
We can link the implementation of the flow, as all of them are implemented in this repo + the github action repo, 
I think it would be helpful to link the entrypoint for our flow:
1. the github action https://github.com/chanzuckerberg/napari-hub-preview-action/blob/main/action.yml
2. the preview script: https://github.com/chanzuckerberg/napari-hub/blob/main/backend/preview/preview.py
3. the frontend readme for page generation: https://github.com/chanzuckerberg/napari-hub/blob/main/frontend/README.md
4. github app responsible for content transfer: https://github.com/chanzuckerberg/napari-hub/blob/dfa9fc6c12388b92db00e9ee432e77a4969a196d/backend/api/app.py#L97

2021-11-12 17:00 UTC, neuromusic requested changes
looks good, pending a couple of changes and feedback on the "known issues"

2021-11-12 17:03 UTC, neuromusic commented on docs/setting-up-preview.md
> +
```suggestion
# For more info on this action, see https://github.com/apps/napari-hub-plugin-preview

```

2021-11-12 22:19 UTC, potating-potato requested changes

2021-11-12 22:19 UTC, potating-potato commented on docs/setting-up-preview.md
> +
this this is renamed, we also need to rename the comparison in the github app: https://github.com/chanzuckerberg/napari-hub/blob/dfa9fc6c12388b92db00e9ee432e77a4969a196d/backend/api/model.py#L231

2021-11-14 23:25 UTC, DragaDoncila commented on docs/setting-up-preview.md
> +
Hmm ok @neuromusic how strongly do you feel about the workflow being called "napari hub Preview Page" instead of just "Preview Page"?

I'll also add text to the documentation to mention that we search by that name.

2021-11-14 23:43 UTC, DragaDoncila commented
@neuromusic have now updated the FAQ copy as well if you want to verify - will just need to update the link to the main doc.

2021-11-14 23:52 UTC, DragaDoncila commented
At this stage I think this is ready for final review @potating-potato @neuromusic.

I think for the pilot program we need:
- this doc & FAQs updated
- action readme updated ([PR here](https://github.com/chanzuckerberg/napari-hub-preview-action/pull/2))
- app readme updated - I'm not sure how to go about this?

We can then update napari's docs in a later PR?

2021-11-15 17:57 UTC, neuromusic commented
re: the FAQ update, this feature is not yet "public" because we do not yet have an updated Privacy Policy and ToS, so we cannot list this in the FAQ yet.

2021-11-15 17:59 UTC, neuromusic commented on docs/setting-up-preview.md
> +
thanks. rationale is that, without a name that clearly links this action to napari + napari hub, it might not be clear to the user 6 months later why they installed this action or what it does

2021-11-15 19:22 UTC, neuromusic approved these changes

2021-11-15 19:47 UTC, potating-potato approved these changes

2021-11-15 20:14 UTC, merged