Make plugin preview page comments less persistent
chanzuckerberg/napari-hub pull request #460
Opened 2022-04-12 02:38 UTC by snigdhaAgarwal

New Logic: 
- Updates the preview page comment in place so multiple comments are not made
   - Check for existing comments in the PR and then updates if exists or creates a new one if not found
- Current Timestamp is added to keep track of when the comment was updated. Users can also keep track of when the comment was updated in the 'Edited' dropdown as shown below
<img width="932" alt="Screen Shot 2022-04-22 at 12 14 39 AM" src="https://user-images.githubusercontent.com/1850984/164599633-0c5a3d51-61f7-49ca-bb5f-88c277a962d3.png">

--------------------------------------------------------------------------------

Old logic:
- Removes the comment making line from when the workflow run is completed. 
- Created a separate method for making the preview page comment when a pull request is created.

Both these changes will make the comment only once per PR and not every time a commit is made.

2022-04-20 19:00 UTC, codemonkey800 commented on backend/api/model.py
> +    pull_request.create_comment('Checkout my awesome preview page!! \n'
Should be:

> Preview page for your plugin is ready here

2022-04-20 19:00 UTC, codemonkey800 commented on backend/api/app.py
> +@github_app.on("pull_request.opened")
Thing about this is we'd post the link to the preview page before the build has completed. This might be fine, but curious what @neuromusic thinks

2022-04-20 19:07 UTC, klai95 commented on backend/api/model.py
> +
nitpick: I think it would be more consistent for all methods to have the newline or. all methods to not have the newline; in this case, I am referring to preview_page_comment and move_artifact_to_s3

2022-04-20 20:23 UTC, neuromusic commented on backend/api/app.py
> +@github_app.on("pull_request.opened")
+1

2022-04-20 20:25 UTC, neuromusic commented on backend/api/app.py
> +@github_app.on("pull_request.opened")
Part of the concern here is that some developers have installed the app onto repos that are NOT napari plugins so we don't want to post comments unless the preview page build completes successfully.

2022-04-25 16:44 UTC, codemonkey800 approved these changes
this LGTM, awesome work!! 🤩

2022-04-25 21:45 UTC, klai95 approved these changes
LGTM!

2022-04-26 00:28 UTC, neuromusic requested changes
one concern for a possible edge case, otherwise LGTM!

2022-04-26 00:28 UTC, neuromusic commented on backend/api/model.py
> +                if text in comment.body:
what happens if another user happens to type "Preview page for your plugin is ready here:" into their comment? do we also need to make sure that the `napari-hub-bot` wrote the comment?

2022-04-26 01:00 UTC, codemonkey800 commented on backend/api/model.py
> +                if text in comment.body:
ahh I thought about that too but wasn't too concerned with it. Although, we should probably err on the side of caution.  But yeah, given this code, it'll pick the first comment it finds with the string `Preview page for your plugin is ready here:`.

@snigdhaAgarwal is there anyway to detect it coming from a specific user? maybe the `napari-hub` user?
<img width="535" alt="image" src="https://user-images.githubusercontent.com/2176050/165198191-b4526eef-86ee-4a65-98b1-f0e8efcdbddd.png">

2022-04-26 01:31 UTC, snigdhaAgarwal commented on backend/api/model.py
> +                if text in comment.body:
Yes there was. Thanks for noticing this! I just updated it.

2022-04-26 15:53 UTC, neuromusic requested changes

2022-04-26 15:53 UTC, neuromusic commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
love it, however, there's a risk that the name of the napari hub bot might change... I believe it should be possible to check against the "id" of the user (which is a persistent integer identifier): https://docs.github.com/en/rest/issues/comments#get-an-issue-comment

2022-04-27 00:22 UTC, neuromusic commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
@bnelson-czi you're familiar with the Github API... this is the data we have on the user...

``` json
{
  'login': 'test-napari-hub-preview[bot]', 
  'id': 103686277, 
  'node_id': 'BOT_kgDOBi4ghQ', 
  'avatar_url': 'https://avatars.githubusercontent.com/u/1850984?v=4', 
  'gravatar_id': '', 
  'url': 'https://api.github.com/users/test-napari-hub-preview%5Bbot%5D', 
  'html_url': 'https://github.com/apps/test-napari-hub-preview', 
  'followers_url': 'https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/followers', 
  'following_url': '[https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/following{/other_user}](https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/following%7B/other_user%7D)', 
  'gists_url': '[https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/gists{/gist_id}](https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/gists%7B/gist_id%7D)', 
  'starred_url': '[https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/starred{/owner}{/repo}](https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/starred%7B/owner%7D%7B/repo%7D)', 
  'subscriptions_url': 'https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/subscriptions', 
  'organizations_url': 'https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/orgs', 
  'repos_url': 'https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/repos',
  'events_url': '[https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/events{/privacy}](https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/events%7B/privacy%7D)', 
  'received_events_url': 'https://api.github.com/users/test-napari-hub-preview%5Bbot%5D/received_events', 
  'type': 'Bot', 
  'site_admin': False
}
```

Can you confirm @bnelson-czi that the `id` field represents a unique identifier for our bot?

2022-04-27 02:09 UTC, bnelson-czi commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
I agree that we should check a persistent identifier, and yes, `id` should be that field.

There seem to be multiple hub bots, including `napari-hub[bot]` and `napari-hub-preview[bot]`. Only the former has posted comments in plugin repos AFAIK.

2022-04-27 03:57 UTC, neuromusic commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
iirc we renamed `napari-hub-preview[bot]` to `napari-hub[bot]` (and I could imagine we rename again)

2022-04-27 15:47 UTC, bnelson-czi commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
if it was renamed, I thought the `id` would persist but it apparently doesn't

```
{
  "login": "napari-hub[bot]",
  "id": 92606302,
  "node_id": "BOT_kgDOBYUPXg",
  "avatar_url": "https://avatars.githubusercontent.com/in/145260?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/napari-hub%5Bbot%5D",
  "html_url": "https://github.com/apps/napari-hub",
  "followers_url": "https://api.github.com/users/napari-hub%5Bbot%5D/followers",
  "following_url": "https://api.github.com/users/napari-hub%5Bbot%5D/following{/other_user}",
  "gists_url": "https://api.github.com/users/napari-hub%5Bbot%5D/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/napari-hub%5Bbot%5D/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/napari-hub%5Bbot%5D/subscriptions",
  "organizations_url": "https://api.github.com/users/napari-hub%5Bbot%5D/orgs",
  "repos_url": "https://api.github.com/users/napari-hub%5Bbot%5D/repos",
  "events_url": "https://api.github.com/users/napari-hub%5Bbot%5D/events{/privacy}",
  "received_events_url": "https://api.github.com/users/napari-hub%5Bbot%5D/received_events",
  "type": "Bot",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 0,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-10-15T20:30:48Z",
  "updated_at": "2021-11-30T04:21:55Z"
}
```

```
{
  "login": "napari-hub-preview[bot]",
  "id": 92128409,
  "node_id": "BOT_kgDOBX3EmQ",
  "avatar_url": "https://avatars.githubusercontent.com/in/143402?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D",
  "html_url": "https://github.com/apps/napari-hub-preview",
  "followers_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/followers",
  "following_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/following{/other_user}",
  "gists_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/subscriptions",
  "organizations_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/orgs",
  "repos_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/repos",
  "events_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/events{/privacy}",
  "received_events_url": "https://api.github.com/users/napari-hub-preview%5Bbot%5D/received_events",
  "type": "Bot",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 0,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-10-07T23:40:20Z",
  "updated_at": "2021-10-07T23:40:20Z"
}
```

2022-04-27 16:07 UTC, neuromusic commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
@bnelson-czi interesting... 10/7 was super early in the work on this... I wonder if that was actually the same bot?

2022-04-27 16:15 UTC, neuromusic commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
we also went through a process where it was promoted to the marketplace, then reverted (which required some manual intervention by Github)... could be that that process assigned a new identifier to the app

2022-04-27 17:25 UTC, bnelson-czi commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
could we temporarily change the bot's name to see if `id` persists? we could also test it on `test-napari-hub-preview[bot]` that @snigdhaAgarwal showed

2022-04-28 16:28 UTC, snigdhaAgarwal commented on backend/api/model.py
> +                if text in comment.body and comment.user == 'napari-hub[bot]':
@bnelson-czi, @neuromusic  How about we check for multiple conditions - The text should match, the type should be 'Bot' and the name should have [bot] in it. Do you think there might arise scenarios where these can be broken?

2022-04-28 23:51 UTC, neuromusic approved these changes

2022-04-29 20:08 UTC, merged

2022-04-29 20:19 UTC, neuromusic commented
🎉