Manifest available through API call
chanzuckerberg/napari-hub pull request #471
Opened 2022-04-22 19:38 UTC by snigdhaAgarwal

Changes in model.py : Mimics the behaviour of get_plugin which makes version.json available
Changes in app.py: After receiving the manifest dictionary from get_manifest function, it checks for the value of process_count to throw the appropriate error. I have set 503 as the code for temporarily unavailable as opposed to some 3xx code based on [this](https://airbrake.io/blog/http-errors/503-service-unavailable#:~:text=A%20503%20Service%20Unavailable%20Error,server%20that's%20down%20for%20maintenance.).

2022-04-22 19:47 UTC, klai95 commented on backend/api/app.py
> +    if manifest and 'process_count' in manifest:
I think you need to have a case for `if manifest not in manifest`, and then create the manifest file and write `process_count = 0` in the logic for that. part of code

2022-04-22 19:47 UTC, potating-potato requested changes
there may be more thoughts required on handling the file, it should be handling yaml file instead of json

2022-04-22 19:47 UTC, potating-potato commented on backend/api/app.py
> +            return app.make_response(("Temporarily Unavailable", 503))
good call for the 503! you may want to use "Retry-After" header in conjunction

2022-04-22 19:47 UTC, potating-potato commented on backend/api/app.py
> +        if manifest['process_count'] >= max_failure_tries:
I believe this manifest should be YAML, and not json?

2022-04-22 19:47 UTC, potating-potato commented on backend/api/model.py
> +    plugin = get_cache(f'cache/{plugin}/{version}.yaml')
the manifest is YAML file, may need additional processing to read it to a map

2022-04-22 19:51 UTC, potating-potato commented on backend/api/app.py
> +            return app.make_response(("Temporarily Unavailable", 503))
see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

2022-04-22 19:51 UTC, klai95 commented on backend/api/app.py
> +    if manifest and 'process_count' in manifest:
I think `if manifest` and `else` should be the two conditions that separate out the logic 

if manifest: 
  if `process_count` in manifest and manifest['process_count'] >= max_failure_tries: 404
  if `process_count` in manifest and manifest['process_count'] < max_failure_tries: 503
else:
  create manifest file
  manifest['process_count'] = 0

2022-04-22 19:54 UTC, klai95 commented on backend/api/app.py
> +    if manifest and 'process_count' in manifest:
i can't get the indentation correct but hopefully this makes sense

2022-04-22 19:56 UTC, klai95 commented on backend/api/model.py
> +    elif version is None:
what about the case where plugin is in list of plugins and version is provided

2022-04-22 20:00 UTC, snigdhaAgarwal commented on backend/api/app.py
> +            return app.make_response(("Temporarily Unavailable", 503))
What should be the value for Retry-After?

2022-04-22 20:04 UTC, snigdhaAgarwal commented on backend/api/app.py
> +        if manifest['process_count'] >= max_failure_tries:
get_manifest will return a dictionary

2022-04-22 20:57 UTC, snigdhaAgarwal commented on backend/api/model.py
> +    elif version is None:
I think the code that follows is de-facto following that condition. The if-else is just for setting the version number.

2022-04-25 14:40 UTC, potating-potato reviewed
in general looks good to me, can you please deploy this remotely (push to a branch named dev-*) and check the behavior there as well, just in case? thanks!


ps. before merging, please update the API doc to include the new endpoint and the possible error codes

2022-04-25 21:40 UTC, klai95 commented on backend/api/app.py
> +    if 'process_count' in manifest:
Where are you checking for existence of manifest file?

2022-04-25 23:15 UTC, potating-potato commented on backend/api/model.py
> +from flask import abort
I searched the code change and didn't find a reference to this import, can you please point me to where this is used? or maybe you are planning to drop it?

2022-04-26 00:58 UTC, snigdhaAgarwal commented on backend/api/model.py
> +from flask import abort
Oh its' not used anywhere. I need to remove it. I resolved the conversation before committing the changes. Pushing the change now

2022-04-26 01:01 UTC, snigdhaAgarwal commented on backend/api/app.py
> +    if 'process_count' in manifest:
That logic is in [model.py](https://github.com/chanzuckerberg/napari-hub/blob/d2dd8d780a6e3a639d78896100f3ecb989db3a54/backend/api/model.py#L95) get_manifest function. If it's unable to get the yaml file it returns a dictionary with just process_count set to 0.

2022-04-26 15:38 UTC, potating-potato commented on backend/api/s3.py
> +def get_cache_manifest(key: str) -> Union[Dict, List, None]:
one minor thing, it is possible to reduce the code duplication on the caching of different format, potentially you can extend the original method to support another parameter, say "format", and default to json handling

2022-04-26 22:06 UTC, klai95 commented on backend/api/model.py
> +    plugins = get_valid_plugins()
We should avoid calling get_valid_plugins() for performance reasons

2022-04-27 21:55 UTC, potating-potato commented on backend/api/app.py
> +            response = app.make_response(("Temporarily Unavailable my plugin!", 503))
typo?

2022-04-27 21:58 UTC, potating-potato commented on backend/requirements.txt
> +cryptography==36.0.2
looking at some related discussions I think we should add pyOpenSSL to our dependency list and see if this fixed the problem, instead of binning to older version of cryptography

2022-04-27 22:27 UTC, klai95 commented on backend/api/app.py
> +
nit: we can get rid of this newline

2022-04-27 22:28 UTC, klai95 commented on backend/api/app.py
> +            response = app.make_response(("Temporarily Unavailable. Attempting to build manifest. Please check back "
nit: I think there is an additional space after `back`

2022-04-27 22:38 UTC, DragaDoncila requested changes
Looks good just requested a slight rearranging of the api endpoint flow for clarity. I also notice we're writing to `cache/{plugin}/{version}.yml` not `cache/manifests/{plugin}/{version}.yml` and just want to make sure that's an explicit choice?

2022-04-27 22:38 UTC, DragaDoncila commented on backend/api/app.py
> +    if 'process_count' in manifest:
I would update this flow to be a bit easier to follow:

```python
if not manifest:
    return 404

if process_count not in manifest:
    return manifest
    
current_tries = manifest['process_count']
if current_tries >= max_failure_tries:
    return 404
else:
    return 503
```

2022-04-27 22:42 UTC, DragaDoncila commented on backend/api/app.py
> +            response = app.make_response(("Temporarily Unavailable my plugin!", 503))
Debugging lol - I think that's been fixed in latest changes

2022-04-28 16:13 UTC, potating-potato commented
This is looking good, thanks so much @snigdhaAgarwal!

2022-04-28 16:14 UTC, potating-potato approved these changes

2022-04-28 18:20 UTC, klai95 approved these changes
Looks good to me. Good job!

2022-04-28 19:57 UTC, DragaDoncila approved these changes
Looks good to me! Great work @snigdhaAgarwal! 🎉

2022-04-28 20:11 UTC, potating-potato commented on backend/api/templates/swagger.yml
> +      responses:
need to include 404 and 503 here

2022-04-28 20:12 UTC, potating-potato commented
one last thing: we didn't include the HTTP 404 and 503 in the API doc, once addressed we can merge this PR

2022-04-28 23:42 UTC, klai95 commented
> > Looks good just requested a slight rearranging of the api endpoint flow for clarity. I also notice we're writing to `cache/{plugin}/{version}.yml` not `cache/manifests/{plugin}/{version}.yml` and just want to make sure that's an explicit choice?
> 
> I wanted to stick to the same format as 'cache/{plugin}/{version}.json' for the yaml.

Yeah I agree. This would be consistent with the current implementation and structure on Amazon S3

2022-04-29 20:02 UTC, merged