npe2 plugin type + reader/writer metadata UI
chanzuckerberg/napari-hub pull request #472
Opened 2022-04-25 19:45 UTC by codemonkey800

Implements:
- https://github.com/chanzuckerberg/napari-hub/issues/425
- https://github.com/chanzuckerberg/napari-hub/issues/467

## Demos

https://napari-hub-npe2.vercel.app

<img width="242" alt="image" src="https://user-images.githubusercontent.com/2176050/165162574-5c0cad88-e3e1-4d50-bfc7-2ccd34744a30.png">

<img width="244" alt="image" src="https://user-images.githubusercontent.com/2176050/165162584-6e48fd91-b87b-49fb-8cab-0a00b0576342.png">

<img width="241" alt="image" src="https://user-images.githubusercontent.com/2176050/165162608-e3956e26-3112-46cf-8c6e-dd184861a108.png">

<img width="237" alt="image" src="https://user-images.githubusercontent.com/2176050/165162626-d66479ba-051f-4d01-9e45-1e0b31266edd.png">

2022-04-25 20:19 UTC, codemonkey800 commented
@liaprins-czi @neuromusic oh yeah also, here's a demo with npe2 stuff on the preview page:

https://napari-hub-npe2-preview-page.vercel.app/?enable-feature=npe2

2022-04-25 21:18 UTC, neuromusic requested changes
Love the alphabetical extensions.

For "Plugin Type", can we be more explicit with the ordering... e.g., keep Reader/Writer next to each other and roughly prioritize the Plugin Types?

Proposed:

- Widget
- Reader
- Writer
- Sample Data
- Theme

2022-04-25 21:23 UTC, codemonkey800 commented
> Love the alphabetical extensions.

Haha this was unintentional, I think I made it alphabetical in the data, but we can sort it explicitly to make it look nice

> For "Plugin Type", can we be more explicit with the ordering... e.g., keep Reader/Writer next to each other and roughly prioritize the Plugin Types?

sounds good to me!

2022-04-25 21:32 UTC, neuromusic commented
> we can sort it explicitly to make it look nice

yes! I think this would be great, especially as the list grows

2022-04-25 21:50 UTC, codemonkey800 commented
@neuromusic alright I've sorted the plugin types and file extensions: https://napari-hub-npe2.vercel.app 🔥

2022-04-25 22:22 UTC, DragaDoncila commented
@neuromusic are we 100% on going with `widget` for the analysis style plugins? I know it's the canonical term but I remember there being some discussion about it being potentially confusing for non-technical/new to napari users.

2022-04-25 22:52 UTC, liaprins-czi approved these changes
Looks awesome to me! Thanks! 🫠

2022-04-26 20:15 UTC, kne42 approved these changes
a few nitpicks otherwise lgtm

2022-04-26 20:15 UTC, kne42 commented on frontend/i18n/en/homePage.json
> +        "tooltip": "Sample Data plugins let users access sample data in napari."
find it weird how "data" is capitalized in the tooltip but not the label

2022-04-26 20:15 UTC, kne42 commented on frontend/src/components/MetadataList/MetadataList.tsx
> +              !inline && !inlineList && 'mb-3',
found this a little bit confusing, so basically it's equivalent to:
```
if inline: 'inline mr-2'
elif inlineList: ''
else: 'mb-3'
```

maybe include a comment about why inlineLists don't need any margins for better human readability

2022-04-26 20:15 UTC, kne42 commented on frontend/src/components/PluginDetails/PluginMetadata.tsx
> +              {renderItemList('operatingSystems')}
not related to this PR but was wondering why you explicitly have a function for rendering a single item item list instead of checking in the function if there were multiple items present

2022-04-26 20:23 UTC, neuromusic commented
@DragaDoncila you're right, earlier versions had "extension"... while I personally love this, for the launch, I think we should try to be consistent with the term used throughout napari.org and the codebase.

as we tackle usability testing, this might be a good question to ask end users, though... what their understanding/assumptions are about each of these plugin types

2022-04-26 20:36 UTC, codemonkey800 commented on frontend/src/components/PluginDetails/PluginMetadata.tsx
> +              {renderItemList('operatingSystems')}
haha didn't think about it at the time, we might be able to do that. the code for both functions are similar

2022-04-26 21:42 UTC, neuromusic approved these changes
looks great!

2022-04-27 18:44 UTC, codemonkey800 commented on frontend/src/components/MetadataList/MetadataList.tsx
> +              !inline && !inlineList && 'mb-3',
actually this styling is confusing. I fixed instead by adding a margin top to each list item for spacing

2022-04-27 19:06 UTC, merged