Backend NPE2 Feature
chanzuckerberg/napari-hub pull request #520
Opened 2022-06-01 22:31 UTC by klai95

2022-06-01 22:39 UTC, potating-potato commented on backend/api/model.py
> +            return {'error': error}
this is not documented in the API spec, you should either:
* include this behavior in API documentation or
* roll back the behavior to return empty dict

alternatively, if we are modifying the API spec, I would recommend doing proper HTTP code with the error message, this would be a 404 I think

2022-06-01 22:41 UTC, DragaDoncila commented on backend/api/model.py
> +            return {'error': error}
lol yep we were just going to ping you here. I think this should still just be an empty dict, I don't think there's a reason to throw an additional error. This is leftover from debugging I think

2022-06-01 22:41 UTC, potating-potato commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
we should move the build manifest logic to during build process. The get_plugin should only fetch existing file

2022-06-01 22:42 UTC, potating-potato commented on backend/api/model.py
> +    manifest_metadata = get_plugin_metadata_async(plugins, build_manifest_metadata)
nit picking: group the getter for metadata together, instead of being separate by the exclude

2022-06-01 22:45 UTC, DragaDoncila commented on backend/requirements.txt
> +npe2 # for npe2 manifest work and could potentially be moved to installation at runtime
I actually don't think we *could* get away without npe2, so we should remove this comment

2022-06-01 22:46 UTC, potating-potato commented on backend/requirements.txt
> +npe2 # for npe2 manifest work and could potentially be moved to installation at runtime
I see we have one already under plugins, should remove this one here then

2022-06-01 22:47 UTC, DragaDoncila commented on backend/utils/utils.py
> +        'writer_save_layers': writer_save_layers,
```suggestion
    manifest_attributes = {
        'display_name': '',
        'plugin_types': [],
        'reader_file_extensions': [],
        'writer_file_extensions': [],
        'writer_save_layers': [],
```

2022-06-01 22:50 UTC, DragaDoncila commented on plugins/get_plugin_manifest.py
> +def lambda_handler(event, context):
I think we should rename this to something like "generate_manifest" or something more explicit

2022-06-01 22:50 UTC, DragaDoncila commented on plugins/Dockerfile
> +CMD ["get_plugin_manifest.lambda_handler"]
if we change `lambda_handler` must change this here too

2022-06-01 22:52 UTC, DragaDoncila commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
We don't write a separate `manifest.json` of the parsed fields of the raw manifest, so that's why we're parsing the raw manifest here. We could parse at build time, and write a separate json, but I guess I don't see the benefit of that, since we're merging them at runtime anyway?

2022-06-01 22:53 UTC, DragaDoncila commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
I guess this would help us keep `npe2` dep out of backend though so maybe worth it

2022-06-02 00:59 UTC, klai95 commented on plugins/Dockerfile
> +CMD ["get_plugin_manifest.lambda_handler"]
Resolved

2022-06-02 00:59 UTC, klai95 commented on plugins/get_plugin_manifest.py
> +def lambda_handler(event, context):
Resolved

2022-06-02 00:59 UTC, klai95 commented on backend/utils/utils.py
> +        'writer_save_layers': writer_save_layers,
Resolved

2022-06-02 00:59 UTC, klai95 commented on backend/requirements.txt
> +npe2 # for npe2 manifest work and could potentially be moved to installation at runtime
Resolved

2022-06-02 01:00 UTC, klai95 commented on backend/api/model.py
> +    manifest_metadata = get_plugin_metadata_async(plugins, build_manifest_metadata)
Resolved

2022-06-02 01:01 UTC, klai95 commented on backend/api/model.py
> +            return {'error': error}
Resolved

2022-06-02 17:35 UTC, potating-potato commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
maybe I should clarify what I meant:
right now the logic is as follows:
UPDATE: build json and write json to cache
GETTER: read cache json

with manifest we should do the same, just that we are nesting both:
UPDATE: build json and yaml, write json and yaml to cache
GETTER: read cached json, read cached yaml, nest them

2022-06-02 17:42 UTC, potating-potato commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
another confusion I do have is around the npe2 dependency: all of the processing logic should happen in the installer lambda, and supposedly the API model should take everything in the yaml and aggregate it to the get_plugin call, without understanding what is in there. Is there something I am missing here?

2022-06-02 20:45 UTC, DragaDoncila commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
I think there's two points here where there's some confusion for us. 

- The first is that `get_plugin` calls `build_manifest_metadata`. If I understand correctly, you're wondering why this needs to be called if the yaml was already written in `lambda_handler`. This function's job is just to call `get_manifest` and then parse the raw manifest into the fields expected by the frontend. However, `get_manifest` also writes the `process_count=0` to a new file if it can't find the manifest. This is *the* trigger for the `lambda_handler` - if we don't call this method here, then neither individual plugins nor `index.json` will have the manifest metadata available until someone explicitly requests the raw manifest via `/manifest/plugin-name`. This is because we rely on the `process_count` writing to trigger the lambda. Once we move to SQS as you suggested, this may no longer be so weird.
- The second point of confusion is why we need `npe2` in the `backend` when the yaml has already been written by the `lambda_handler`. This is again because the raw manifest is different to the fields expected by the frontend, which is aggregate metadata. We read the raw manifest with `npe2`s own utilities - this is part of the tech spec and is imo the only sane way to do it, because this helps us ensure we are always up to date with the manifest schema, and allows us to trivially handle changes to the manifest spec. 

If our desire is not to have an `npe2` dependency in the backend, then my proposed solution is that we parse the raw manifest in `lambda_handler` into the aggregate fields required by the front end, and write this to an entirely separate json. Then we could just read and merge them in `get_plugin`. So, the cache folder for any individual plugin would have e.g.
- `0.0.1.json` (original plugin metadata, has nothing to do with npe2
- `0.0.1.yaml` (raw manifest)
- `0.0.1.manifest.json` (aggregate manifest fields for frontend)

Note that this solution would *not* solve the issue of writing `process_count` when we call `get_plugin`, because we *still need the trigger* to update `index.json` and the individual plugin caches.

2022-06-06 19:31 UTC, potating-potato commented on backend/api/model.py
> +            _, manifest_attributes = build_manifest_metadata(plugin, version)
ok I think I am aligned on the second point, I didn't know the raw manifest is a different thing and needs to be processed. In this case, my recommendation would be the following:
/manifest/{plugin} returns the raw manifest as before
/plugins/{plugin} reads the json and the raw manifest, returns the json with the entire manifest as one attribute, and we copy the entire manifest into it without modification. (This requires our frontend to look inside this manifest attribute though). It would look like: {"name": "plugin",..., "manifest": {converted manifest in json}}

We maintain one ground truth data source by having them as json and yaml file, while we aggregate them at run time with 2 cache lookup, which shouldn't be too bad. Thoughts?

2022-06-08 06:02 UTC, richaagarwal commented
@klai95 I know this is still in a draft stage, but when you get a chance, could you fill out the PR description to give a high-level summary of the changes this is introducing?  I think you mentioned the functionality here covers more than what's listed in https://github.com/chanzuckerberg/napari-hub/issues/468, so it could be helpful to note those additions here, and/or let me know if we should create another GitHub issue to capture those.

2022-06-08 06:40 UTC, richaagarwal commented on backend/api/s3.py
> +    except ClientError:
When would we expect something to not be in the cache?

2022-06-08 18:48 UTC, klai95 commented
> @klai95 I know this is still in a draft stage, but when you get a chance, could you fill out the PR description to give a high-level summary of the changes this is introducing? I think you mentioned the functionality here covers more than what's listed in #468, so it could be helpful to note those additions here, and/or let me know if we should create another GitHub issue to capture those.

Will do, thank you!

2022-06-08 18:54 UTC, klai95 commented on backend/api/s3.py
> +    except ClientError:
If a plugin has not started the installation process, there would be no manifest file in the s3 cache for the plugin. The lambda functions are triggered by s3 file creation / deletion at the moment, which means that if I manually delete a plugin's manifest file (.yaml) on s3, via the Cloudwatch event which gets executed every 5 minutes, the backend codebase will execute and as a result a new manifest file (.yaml) would be created on s3 for the plugin. The same logic applies in the case in which a new version of the plugin file (.json), e.g. version 0.0.2, has been created. This creation of the new version of the plugin will also trigger the backend codebase to generate a corresponding manifest file (.yaml). It is important to note that, for any version of the plugin, once the manifest file is written (successful or not), it would not be changed. This would mean that any metadata added to the manifest schema thereafter would reflect in future versions of the manifest file. I hope this helps, and please let me know if I can clarify further!

2022-06-09 18:56 UTC, richaagarwal commented on backend/api/app.py
> +    try:
I'm curious about this - is there a reason we can't print the error outright?  Also, where do the print statements go? (It's in my notes that at some point we should set up more robust logging, but would love to understand current state first!)

2022-06-13 22:39 UTC, klai95 commented on backend/api/app.py
> +    try:
The print statements appear in log files on Cloudwatch! As for the reason we can't print the error outright, to be honest I am not sure, as that was the way the code was before I joined. I do tend to agree with a more robust logging approach that can expedite development velocity, so I think that is a good future work item to capture, although I would say that particular work would not be related to this PR.

2022-06-13 22:43 UTC, richaagarwal commented on backend/api/app.py
> +    try:
Thanks for the context!  I'll capture this for future work; agreed it's out of scope for this PR.

2022-06-13 22:47 UTC, klai95 commented
> @klai95 I know this is still in a draft stage, but when you get a chance, could you fill out the PR description to give a high-level summary of the changes this is introducing? I think you mentioned the functionality here covers more than what's listed in #468, so it could be helpful to note those additions here, and/or let me know if we should create another GitHub issue to capture those.

Just added the description for PR!

2022-06-13 23:03 UTC, potating-potato commented on backend/api/app.py
> +    try:
fwiw, it seems we don't need to raise, supposedly the traceback call below would work without the raise

2022-06-13 23:06 UTC, potating-potato approved these changes
LGTM

please verify the frontend page and everything works as intended before merge

p.s. Happy to answer terraform related questions and comments

p.p.s. @codemonkey800 is there feature flag we can enable to see the npe2 related changes? btw here's the frontend page https://add-npe2-lambda-frontend.dev.imaging.cziscience.com/plugins/affinder

2022-06-14 00:40 UTC, codemonkey800 approved these changes

2022-06-14 03:41 UTC, potating-potato commented on .happy/terraform/modules/lambda-container/variables.tf
> +  default = 0
this should be default to 2

2022-06-14 16:14 UTC, codemonkey800 commented
@potating-potato @klai95 you can check for npe2 using this URL:

https://add-npe2-lambda-frontend.dev.imaging.cziscience.com/plugins/affinder?enable-feature=npe2

however, I do not see any plugin data in the frontend or API 🤔 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2176050/173625674-169737e2-6ce2-4836-aebd-c9808e4929d2.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2176050/173625710-317a2b85-c8b0-4552-b939-098156c823ac.png">

2022-06-14 16:37 UTC, potating-potato commented on backend/utils/utils.py
> +        if manifest_contributions.get('readers'):
should be checked with "if readers in ..." to be pythonic

2022-06-14 20:07 UTC, potating-potato requested changes
need to update the exception message

2022-06-14 20:30 UTC, potating-potato commented
> > need to update the exception message
> 
> can you clarify what we need to update with the exception message itself? Right now we have process_count and error_message

https://github.com/chanzuckerberg/napari-hub/pull/520/files#r896239190

2022-06-14 20:32 UTC, potating-potato commented on backend/utils/utils.py
> +def parse_manifest(manifest: Optional[dict] = None):
if you are struggling with these "in" checks. see if you can convert the manifest to be default dicts, that at least get rid of key error with

2022-06-14 20:32 UTC, potating-potato commented on backend/utils/utils.py
> +def parse_manifest(manifest: Optional[dict] = None):
https://realpython.com/python-defaultdict/

2022-06-14 20:39 UTC, DragaDoncila commented on plugins/_tests/test_manifest.py
> +from plugins.get_plugin_manifest import parse_manifest
this whole test file is useless atm because we're parsing using a dictionary rather than the plugin manifest. This needs to be refactored and moved to `backend/utils/_tests`

2022-06-14 20:51 UTC, potating-potato commented
> however, I do not see any plugin data in the frontend or API 🤔

@codemonkey800 
they maybe emptying data to test the update mechanism, right now the manifest API is outputting https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/add-npe2-lambda/manifest/affinder

same for the https://6vwmwypt38.execute-api.us-west-2.amazonaws.com/add-npe2-lambda/plugins/affinder

@klai95 the manifest API is not outputting format to be application/yaml, it is showing text/html hence the rendering is weird

2022-06-14 22:22 UTC, potating-potato commented on backend/api/app.py
> +import traceback
this is not used. I meant you could do the same print as before, without having to reraise the exception

2022-06-14 22:24 UTC, potating-potato commented on backend/api/s3.py
> +def is_npe2_plugin(plugin, version):
second this opinion. There are 2 part of logic in here, one is fetch the file, the other is making a decision based on the file, should separate and put the logic in the correct place

2022-06-15 03:15 UTC, klai95 commented
> @potating-potato @klai95 you can check for npe2 using this URL:
> 
> https://add-npe2-lambda-frontend.dev.imaging.cziscience.com/plugins/affinder?enable-feature=npe2
> 
> however, I do not see any plugin data in the frontend or API 🤔
> 
> <img alt="image" width="461" src="https://user-images.githubusercontent.com/2176050/173625674-169737e2-6ce2-4836-aebd-c9808e4929d2.png">
> 
> <img alt="image" width="773" src="https://user-images.githubusercontent.com/2176050/173625710-317a2b85-c8b0-4552-b939-098156c823ac.png">

Updated frontend link: https://dev-add-npe2-lambda-frontend.dev.imaging.cziscience.com/plugins/affinder?enable-feature=npe2

2022-06-15 03:29 UTC, potating-potato approved these changes

2022-06-15 03:29 UTC, merged