Analytics for create a new collection
chanzuckerberg/napari-hub pull request #554
Opened 2022-06-14 18:29 UTC by codemonkey800

Closes #513

2022-06-15 20:36 UTC, neuromusic requested changes
looks good, however, the plausible "goals" are getting a bit unwieldy. we should consider a naming convention for better tracking. proposed a revision to this goal here (but requires change in plausible, too)

2022-06-16 17:24 UTC, neuromusic approved these changes

2022-06-16 18:38 UTC, richaagarwal commented on frontend/src/hooks/usePlausible.ts
> +  'CTA: New Collection': unknown;
What does "unknown" signify here?

2022-06-16 19:18 UTC, codemonkey800 commented on frontend/src/hooks/usePlausible.ts
> +  'CTA: New Collection': unknown;
this represents the type of the data payload for the event. for example, here's what it is for filters:

https://github.com/chanzuckerberg/napari-hub/blob/3e714bd1b264c69763a580e7d6a6c00a63f113ac/frontend/src/hooks/usePlausible.ts#L21-L25

since the only thing we need from this event is whether it was fired or not, we don't really need a payload type, so I passed in `unknown` for now. check this out for more info on the `unknown` type: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

2022-06-18 00:25 UTC, richaagarwal commented on frontend/src/hooks/usePlausible.ts
> +  'CTA: New Collection': unknown;
Ah makes sense! Thanks for the overview!

2022-06-22 20:40 UTC, merged