Use static values for Python Version and Operating System filters
chanzuckerberg/napari-hub pull request #58
Opened 2021-05-25 23:10 UTC by codemonkey800

## Description

Follow up from slack discussion: https://chanzuckerbergteam.slack.com/archives/C01NES8FB27/p1621979369047400

2021-05-25 23:38 UTC, justinelarsen commented
@codemonkey800 I don't think the slack discussion is publicly available. Could you summarize it here?

2021-05-25 23:53 UTC, justinelarsen requested changes
I left some comments. Since the options are static, I'm wondering if we can extract them so that they are easier to make updates in the future. I saw that they were duplicated and may make it more difficult to maintain. Thanks for addressing!

2021-05-25 23:53 UTC, justinelarsen commented on client/src/context/search/filter.types.ts
> +  operatingSystems: OperatingSystemState;
Update name for consistency, above two include "FormState" whereas the new two are only "State".

2021-05-25 23:53 UTC, justinelarsen commented on client/src/context/search/filter.utils.ts
> +    operatingSystems: {
Is there a way to store this data so that we're not repeating it multiple times? I'm thinking about the maintenance of this if we have to update like adding Python versions for example. It looks like it's repeated twice in this PR, here and also in client/src/context/search/filter.types.ts. Also, it may introduce bugs if there are discrepancies.

2021-05-26 00:18 UTC, codemonkey800 commented on client/src/context/search/filter.utils.ts
> +    operatingSystems: {
Thankfully TypeScript would actually catch whatever discrepancies if we ever encounter any.

However, I agree it's better if we only have to update one object vs two. I updated the PR to store the versions in an array so we only have to update one place for a new Python version

2021-05-26 15:28 UTC, kne42 commented on client/src/context/search/filter.utils.ts
> +const SUPPORTED_PYTHON_VERSIONS = ['3.7', '3.8', '3.9'];
since we were talking about how these should be tied to the python versions napari supports, maybe in the future this value can be pulled somehow from the napari pypi info so we don't need to update it manually. thoughts @justinelarsen @neuromusic?

2021-05-26 15:49 UTC, codemonkey800 commented on client/src/context/search/filter.utils.ts
> +const SUPPORTED_PYTHON_VERSIONS = ['3.7', '3.8', '3.9'];
Was thinking the same thing too. Not sure about specific strategies, but maybe we can use the `python_requires` property on the napari repo: https://github.com/napari/napari/blob/46f295b599269bc79485d6d7febf1265a4fc7c65/setup.cfg#L38

Or maybe we can keep a JSON file with these versions somewhere on a GitHub repo that can be updated independently from the code.

2021-05-26 16:45 UTC, justinelarsen commented on client/src/context/search/filter.utils.ts
> +const SUPPORTED_PYTHON_VERSIONS = ['3.7', '3.8', '3.9'];
I agree, dynamic would be better. "python_requires" property sounds good to me. @neuromusic What do you think?

2021-05-26 19:26 UTC, merged