Check plugin version before indexing
chanzuckerberg/napari-hub pull request #624
Opened 2022-08-03 18:03 UTC by potating-potato

closes #611 

perform a version check when indexing plugin metadata to prevent pypi api race condition, where the listing reports a newer version but history API is not up to date to use that version.

2022-08-03 18:17 UTC, lgan-czi submitted a review, later dismissed
LGTM

2022-08-03 18:24 UTC, lgan-czi commented
The other place it's used is in is preview.py, not sure if preview.py is affected by the versioning issue too
<img width="1134" alt="Screen Shot 2022-08-03 at 11 23 53 AM" src="https://user-images.githubusercontent.com/106401390/182681463-7249b86a-7884-4fdc-ad7c-4d51bfcb35e4.png">

2022-08-03 19:01 UTC, klai95 approved these changes
LGTM

2022-08-03 19:05 UTC, richaagarwal commented
I think this addresses one of the issues brought up in #611, but we still don't know why there's sometimes a delay before a plugin shows up at all, right?

2022-08-03 19:07 UTC, klai95 commented on backend/utils/pypi.py
> +    # versioned url https://pypi.org/pypi/{plugin}/{version}/json does not track history anymore.
Could you provide some context as to when https://pypi.org/pypi/{plugin}/{version}/json no longer tracked history anymore?

2022-08-03 19:11 UTC, lgan-czi commented on backend/utils/pypi.py
> +    # versioned url https://pypi.org/pypi/{plugin}/{version}/json does not track history anymore.
Apparently including the previous history in the versioned API was causing stability issues with pypi

2022-08-03 19:13 UTC, lgan-czi commented on backend/utils/pypi.py
> +    # versioned url https://pypi.org/pypi/{plugin}/{version}/json does not track history anymore.
Here's a link to the discussion pypi had https://github.com/pypi/warehouse/pull/11775

2022-08-03 19:15 UTC, richaagarwal commented on backend/utils/pypi.py
> +    # versioned url https://pypi.org/pypi/{plugin}/{version}/json does not track history anymore.
Ziyang linked to it in line 52 right below. I'd recommend reading through issue 598 in full.

2022-08-03 19:18 UTC, klai95 commented on backend/utils/pypi.py
> +    # versioned url https://pypi.org/pypi/{plugin}/{version}/json does not track history anymore.
Thanks both, will do

2022-08-03 19:35 UTC, richaagarwal requested changes
.

2022-08-03 19:49 UTC, richaagarwal commented on backend/utils/pypi.py
> +    url = f"https://pypi.org/pypi/{plugin}/json"
I'm actually a little confused now, isn't this going to re-introduce the issue that was fixed in https://github.com/chanzuckerberg/napari-hub/pull/605? The versioned endpoint doesn't have the `releases` data.

2022-08-03 19:55 UTC, richaagarwal commented on backend/api/model.py
> +    metadata = get_plugin_pypi_metadata(plugin, version=version)
What is the purpose of passing in the version here if we never use it?

2022-08-04 02:08 UTC, richaagarwal approved these changes
@potating-potato Thanks for looking into this! Some questions/thoughts:

Is the idea that we would wait for PyPI's non-versioned endpoint to "catch up" to the latest release? https://github.com/chanzuckerberg/napari-hub/issues/611 was originally opened due to an observed lag (>4 hours) before certain plugins were showing up at all on the hub (see https://github.com/chanzuckerberg/napari-hub/issues/611#issuecomment-1192816215). Do you think this lag is due to this issue with PyPI's non-versioned endpoint being out of date? If so, we would still expect this lag to continue, right? 

I'm okay with merging this to fix the particular versioning conflict issue you summarized in https://github.com/chanzuckerberg/napari-hub/issues/611#issuecomment-1204277858, but let's leave https://github.com/chanzuckerberg/napari-hub/issues/611 open so we can also address the lag -- it seems like PyPI's non-versioned endpoint isn't as reliable as we might've thought, and we might need to consider implementing option 2 in https://github.com/chanzuckerberg/napari-hub/issues/608 sooner than later.

2022-08-04 17:59 UTC, potating-potato commented
> @potating-potato Thanks for looking into this! Some questions/thoughts:
> 
> Is the idea that we would wait for PyPI's non-versioned endpoint to "catch up" to the latest release? 

Yes

we would still expect this lag to continue, right?

I am assuming so at the moment, I will keep 611 open

2022-08-04 18:00 UTC, merged