Upgrade to MUI v5 and SDS v7
chanzuckerberg/napari-hub pull request #628
Opened 2022-08-11 17:57 UTC by codemonkey800

## Description

- Updates the hub to use Material UI v5 and SDS, and refactors the codebase to fix any broken changes introduced by the upgrade.
- Update ESLint plugin to use new `@mui` imports
- Refactor theme file into multiple files so we can use MUI theme in TypeScript
- Adds Tailwind config for hub primary and hub gray colors.
- Adds npm scripts for running dev mode using `prod` and `staging` APIs

## Demo

https://napari-hub-mui-upgrade.vercel.app

2022-08-12 16:39 UTC, nclack commented on frontend/src/components/ApplicationProvider.tsx
>            // By default, Material UI will inject styles at the bottom of the
Just double-checking: This comment mentions material-ui. Is it still relevant? Is there a better reference link?

2022-08-12 16:39 UTC, nclack approved these changes
This looks good to me.  Lots of changes, but I double-checked you got all the material-ui stuff, and I like the theme refactoring.

2022-08-12 18:52 UTC, liaprins-czi requested changes
This looks great to me. The only thing is that the category pills on the plugin cards are not quite having equal padding all the way around; I don't know ifI just noticed that now and it was always the case though? If so, it can be a separate bug!
![Screen Shot 2022-08-12 at 11 48 08 AM](https://user-images.githubusercontent.com/53277128/184424706-05b1c373-b42a-4e92-a6e9-9fdf0657695d.png)

The padding that's on the bottom of the pill looks right to me, but on top looks too much and on left looks not enough

2022-08-18 18:30 UTC, merged

2022-08-23 16:07 UTC, liaprins-czi reviewed
The borders on the pills look really good to me now! Thanks!!