Plugin page tabbed navigation
chanzuckerberg/napari-hub pull request #722
Opened 2022-11-01 17:22 UTC by codemonkey800

## Description

Closes #698 

- Implements tabbed navigation UI for the plugin page
- Tabbed nav is hidden behind `activityDashboard` feature flag
- Sets up lazy fetching of activity dashboard data until the tab is loaded
- Clicking on TOC while in separate activity should open description and scroll to selected header

## Demos

https://dev-tab-nav-frontend.dev.imaging.cziscience.com/plugins/napari-demo

### Tabbed navigation

<img width="328" alt="image" src="https://user-images.githubusercontent.com/2176050/199291884-1d33fe68-6662-4d74-9ba7-a3f390cd9f2c.png">

https://user-images.githubusercontent.com/2176050/199292255-e698c70b-d9f4-48c3-b8a2-40ddc7df9f0c.mp4

### Tabs without citations

<img width="286" alt="image" src="https://user-images.githubusercontent.com/2176050/199292395-6f4f2bd3-a51a-4cab-bd4e-c445f3b44e5f.png">

### Tabs skeleton loader

<img width="1440" alt="Screen Shot 2022-11-01 at 10 01 31 AM" src="https://user-images.githubusercontent.com/2176050/199292593-097f28d0-9563-4c14-ad5b-6ae10fb3bddb.png">

### Mobile tabs and overflow

There's a small issue with tabs on smaller screens where switching from the activity dashboard tab to another tab causes the browser to scroll up. I'm not sure what the issue, but I've determined that it's caused by the `ActivityDashboard` component. Since the fix appears non-trivial, this is something we can tackle in a later PR focused on a fix.

https://user-images.githubusercontent.com/2176050/199296042-db855c31-8447-4b74-a4e6-6a09815a3a21.mp4

## Next steps

- Fix issue with scroll to top when activity dashboard unmounts

2022-11-01 18:49 UTC, kandarpksk commented
The tabs work great on desktop! They do look less prominent to me than in the Figma mocks (font seems smaller, tab underline is thinner) and the hover state remains to be implemented, it seems.

In the skeleton loader, could we try a lighter shade of gray for the big box above the tabs and see if that makes it less prominent? @liaprins-czi

2022-11-01 18:56 UTC, manasaV3 approved these changes

2022-11-01 18:56 UTC, manasaV3 commented on frontend/src/components/PluginPage/PluginPageContent.tsx
> +    <>
What is the use of this?

2022-11-01 18:59 UTC, klai95 approved these changes
LGTM!

2022-11-01 21:55 UTC, liaprins-czi requested changes
Thanks for sharing, this is exciting to see the tabs coming to life! There are a few things I think that should be updated from design POV is all:
- [ ] Tab text size is too small, currently 14px but should be 17px
- [ ] The line below the selected tab looks a little too thin (but I can't quite tell from inspecting) but it should be 3px
- [ ] Hovering on a tab should produce the same line but in `Primary500` color ([here's a link to the hover designs)
](https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1390%3A2042)
- [ ] The mobile tab's font size looks too large; I think all the tabs should fit without overflowing the tab area ([Figma design](https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1358%3A2835)). In the designs they are size 11px.

Let me know if you have any questions! Thanks!

2022-11-01 21:57 UTC, liaprins-czi commented
> In the skeleton loader, could we try a lighter shade of gray for the big box above the tabs and see if that makes it less prominent?

I am fine with this if it can apply to all of the skeletons on all the pages. It could be `Gray 100`. But not sure if that's feasible... I will let @codemonkey800 weigh in!

2022-11-01 22:07 UTC, kandarpksk commented
> > In the skeleton loader, could we try a lighter shade of gray for the big box above the tabs and see if that makes it less prominent?
> 
> I am fine with this if it can apply to all of the skeletons on all the pages. It could be `Gray 100`. But not sure if that's feasible... I will let @codemonkey800 weigh in!

Oh, my suggestion was to make the tabs skeleton stand out relative to the big box on top! If we'd like just one shade of gray throughout, I think the current one is fine.

2022-11-02 07:39 UTC, richaagarwal approved these changes

2022-11-02 19:22 UTC, kandarpksk commented
Looks perfect now!

@liaprins-czi did you intend the hover state to apply to the tab currently in focus too? I don't have a strong opinion about it, but maybe the line could remain black to distinguish it as already in focus.
<img width="424" alt="image" src="https://user-images.githubusercontent.com/4083860/199581847-1c2d4f5a-948b-4465-9619-d88292787832.png">

2022-11-04 18:04 UTC, liaprins-czi commented
> Looks perfect now!
> 
> @liaprins-czi did you intend the hover state to apply to the tab currently in focus too? I don't have a strong opinion about it, but maybe the line could remain black to distinguish it as already in focus. <img alt="image" width="424" src="https://user-images.githubusercontent.com/4083860/199581847-1c2d4f5a-948b-4465-9619-d88292787832.png">

Yeah that (being black) is exactly what it should do when its the selected tab... I am going to re-review this PR today and will check

2022-11-04 18:55 UTC, liaprins-czi approved these changes
Looks perfect to me, too! And I thinkit's fien that the selected tab is also able to be hovered upon and show the blue, since this is how the right side nav behaves as well.

2022-11-04 19:24 UTC, merged