View Plugin's Latest Commit
chanzuckerberg/napari-hub pull request #832
Opened 2023-01-13 00:31 UTC by klai95

#closes https://github.com/chanzuckerberg/napari-hub/issues/819

2023-01-23 19:08 UTC, manasaV3 commented on backend/api/s3.py
> +        logging.error(e)
Good idea on logging. :)

2023-01-23 19:08 UTC, manasaV3 commented on backend/api/model.py
> +        'latest commit': latest_commits[plugin],
Having a key without space is the best practice for API response.

2023-01-25 01:14 UTC, manasaV3 commented on backend/api/model.py
> +                data[plugin] = pd.to_datetime(row[1]).strftime(format="%Y-%m-%d %H:%M:%S")
Is there a reason we use pandas here instead of the default python datetime module?

2023-01-25 01:14 UTC, manasaV3 commented on backend/api/model.py
> +        'latest_commit': get_latest_commit(plugin)
Not a blocker: From the principle of single responsibility, it is better to have the s3 module fetch and write objects to s3. We could have this module get the data for the plugin.

2023-01-25 01:16 UTC, manasaV3 commented on backend/api/_tests/test_activity_dashboard.py
> +            latest_commit="2023-01-01 00:00:00",
As `MOCK_PLUGIN_LATEST_COMMIT` is the exact value, we can use the constant here.

2023-01-25 01:16 UTC, klai95 commented on backend/api/model.py
> +                data[plugin] = pd.to_datetime(row[1]).strftime(format="%Y-%m-%d %H:%M:%S")
When I use the default python datetime module, the format of the timestamp comes out to be something like `"2022-11-20+19:18:40", and I want the format to be consistent with what we already have

2023-01-25 01:19 UTC, klai95 commented on backend/api/model.py
> +        'latest_commit': get_latest_commit(plugin)
Sorry, could you clarify what you mean? `get_latest_commit` is a method that is in s3.py used to fetch the data we need, and I am passing the plugin name in model.py

2023-01-25 19:23 UTC, manasaV3 commented on backend/api/model.py
> +        'latest_commit': get_latest_commit(plugin)
It is a good design principle to allow things to have a single functionality. For example, in this case, the s3 module should only be a way to write to s3 and get data from s3. It shouldn't have any knowledge about what the actual data is. It would just fetch the data from s3 and pass it on to this module, which would do the filtering, aka fetching the latest commit by a plugin name. 

I understand that many existing pieces of code do not follow that principle. So, I am not going to block on that. We could consider this in our future designs. :)

2023-01-25 19:28 UTC, manasaV3 commented on backend/api/model.py
> +                data[plugin] = pd.to_datetime(row[1]).strftime(format="%Y-%m-%d %H:%M:%S")
Sorry, if I a missing something obvious here. Could we not use `strftime("%Y-%m-%d %H:%M:%S")`? 

The `strftime(..)` is also available for datetime.
https://docs.python.org/3/library/datetime.html#datetime.date.strftime

2023-01-25 20:41 UTC, klai95 commented on backend/api/model.py
> +        'latest_commit': get_latest_commit(plugin)
That makes sense! I agree that we should do this in the future, since it is a good principle!

2023-01-26 01:13 UTC, manasaV3 requested changes

2023-01-26 01:13 UTC, manasaV3 commented on backend/api/model.py
> +                data[plugin] = pd.to_datetime(row[1]).strftime(format="%Y-%m-%d %H:%M:%S")
Why are we storing the data in the format of `"%Y-%m-%d %H:%M:%S"`? 
It is similar to the format that we are storing the `last_commit` field in the database. The only use case where we use the data must once again transform it at run time. 

It is better to transform it to an epoch timestamp here and store it. It will also make it easier to handle the case where the  `get_latest_commit(..)` returns `None`.

2023-01-26 17:58 UTC, manasaV3 approved these changes

2023-01-26 18:11 UTC, merged

2023-01-27 18:58 UTC, manasaV3 commented
This PR introduces both the data fetch and the API. The data job only runs once a day. So, before we push that to production, we should ensure the required files are available in S3 in the prod stage, so the API does not break.

2023-01-27 19:11 UTC, manasaV3 commented on backend/api/s3.py
> +def get_latest_commit(plugin: str) -> Dict:
Missed this in my earlier review. This method never returns a dict.

2023-01-27 20:01 UTC, klai95 commented on backend/api/s3.py
> +def get_latest_commit(plugin: str) -> Dict:
Curious what is the ask here now that the pr is already merged in? I was just going to make this change in the current PRs I have.

2023-01-27 21:15 UTC, richaagarwal commented on backend/api/model.py
> +    return {'usage': usage_data, 'maintenance': maintenance_data}
Thanks for flagging this @codemonkey800, and sorry I missed this comment earlier. 

Just posting now for posterity: I know we'll be making corresponding frontend changes soon and before the next release. However, in the future, we should make the necessary frontend changes as part of the PR, or have a set of back-end and front-end PRs that get merged in together, so that we can avoid breaking functionality on staging.