View Plugin's Commit Activity
chanzuckerberg/napari-hub pull request #849
Opened 2023-01-27 04:48 UTC by klai95

#closes #820

2023-01-27 06:23 UTC, klai95 commented
`API contract`
```
{
  "maintenance": {
    "stats": {
      "commit_activity_in_last_12_months": [
        {
          "installs": 3,
          "timestamp": 1640995200000
        },
        {
          "installs": 3,
          "timestamp": 1646092800000
        },
        {
          "installs": 13,
          "timestamp": 1648771200000
        },
        {
          "installs": 13,
          "timestamp": 1651363200000
        },
        {
          "installs": 22,
          "timestamp": 1654041600000
        },
        {
          "installs": 25,
          "timestamp": 1656633600000
        },
        {
          "installs": 46,
          "timestamp": 1659312000000
        },
        {
          "installs": 93,
          "timestamp": 1661990400000
        },
        {
          "installs": 47,
          "timestamp": 1664582400000
        },
        {
          "installs": 16,
          "timestamp": 1669852800000
        }
      ],
      "latest_commit_timestamp": 1674591907000
    }
  },
  "usage": {
    "stats": {
      "installs_in_last_30_days": 7,
      "total_installs": 70
    },
    "timeline": [
      {
        "installs": 0,
        "timestamp": 1640995200000
      },
      {
        "installs": 0,
        "timestamp": 1643673600000
      },
      {
        "installs": 0,
        "timestamp": 1646092800000
      },
      {
        "installs": 0,
        "timestamp": 1648771200000
      },
      {
        "installs": 0,
        "timestamp": 1651363200000
      },
      {
        "installs": 20,
        "timestamp": 1654041600000
      },
      {
        "installs": 6,
        "timestamp": 1656633600000
      },
      {
        "installs": 2,
        "timestamp": 1659312000000
      },
      {
        "installs": 4,
        "timestamp": 1661990400000
      },
      {
        "installs": 26,
        "timestamp": 1664582400000
      },
      {
        "installs": 4,
        "timestamp": 1667260800000
      },
      {
        "installs": 1,
        "timestamp": 1669852800000
      }
    ]
  }
}

2023-01-27 06:35 UTC, klai95 commented
Moved https://github.com/chanzuckerberg/napari-hub/issues/820 to `In Code Review`

2023-01-27 21:32 UTC, klai95 commented
@codemonkey800 Commenting here to align on api contract on frontend with respect to the changes in this PR!

2023-01-30 05:50 UTC, manasaV3 commented
As we are trying to have consistency between the `usage` and `maintenance` objects, what are your thoughts on moving the `commit_activity_in_last_12_months` to `timeline` so that we can access it as `maintenance.timeline`? 
Also, by naming it something generic like `timeline`, we can leverage the same field for timelines over different periods in the future.

2023-01-30 05:53 UTC, manasaV3 requested changes

2023-01-30 05:53 UTC, manasaV3 commented on backend/api/model.py
> +    repo_to_plugin_dict = _get_repo_to_plugin_dict()
Instead of fetching this data multiple times, could we fetch it once for every execution of update/activity ?

2023-01-30 06:06 UTC, manasaV3 requested changes

2023-01-30 06:06 UTC, manasaV3 commented on backend/api/model.py
> +        GROUP BY 1,2
Commenting on the relevant PR as well (https://github.com/chanzuckerberg/napari-hub/pull/848#discussion_r1090203226). 
Does fetching just the last year's data maintain parity with usage?

2023-01-30 23:34 UTC, klai95 commented on backend/api/model.py
> +        GROUP BY 1,2
Yes, it does.

2023-01-31 05:07 UTC, klai95 commented on backend/api/s3.py
> +def get_commit_activity(plugin: str) -> Dict:
Since I plan to merge in https://github.com/chanzuckerberg/napari-hub/pull/848 first, I think it would make more sense for me to reflect this particular feedback in that PR, then rebase/merge those changes in this PR.

2023-01-31 05:09 UTC, klai95 commented on backend/api/model.py
> +    repo_to_plugin_dict = _get_repo_to_plugin_dict()
Just to be more specific, is this feedback the same one as https://github.com/chanzuckerberg/napari-hub/pull/848#discussion_r1089316520? If so, then I would just rebase/merge the changes in this PR, just like https://github.com/chanzuckerberg/napari-hub/pull/849#discussion_r1091455489.

2023-01-31 05:21 UTC, klai95 commented on backend/api/model.py
> +                    data[plugin].append({'timestamp': int(pd.to_datetime(row[1]).strftime("%s")) * 1000, 'installs': int(row[2])})
I believe `data[plugin]` results in `KeyError` if plugin does not exist in the `data` dictionary, as shown here: https://realpython.com/python-keyerror/, which is why the original code uses `if plugin not in data` so that the code executes without any errors. 

However, if we use `dict.get(key)` instead of `dict[key]`, then no error would take place, as seen here: https://www.30secondsofcode.org/articles/s/python-dict-getkey-vs-dictkey.


Therefore, I think the following snippet of code would work. Let me know if there is anything I am missing!
```
records_for_plugin = data.get(plugin)
if not records_for_plugin:
    records_for_plugin = []
    data[plugin] = records_for_plugin
records_for_plugin.append({'timestamp': int(pd.to_datetime(row[1]).strftime("%s")) * 1000, 'commits': int(row[2])})

2023-01-31 21:13 UTC, manasaV3 commented
We should also have the items in the `timeline` list say `commits` or something more relevant instead of `installs`.

2023-01-31 21:16 UTC, manasaV3 requested changes

2023-01-31 21:16 UTC, manasaV3 commented on backend/api/model.py
> +                    data[plugin].append({'timestamp': int(pd.to_datetime(row[1]).strftime("%s")) * 1000, 'installs': int(row[2])})
Ahh, good catch on the `KeyError`. Found this other thing we could do using `setdefault`. 
```
data.setdefault(plugin, []).append({'timestamp': int(pd.to_datetime(row[1]).strftime("%s")) * 1000, 'commits': int(row[2])})
```
ref:  https://docs.python.org/3.8/library/stdtypes.html#dict.setdefault

2023-01-31 21:16 UTC, manasaV3 commented on backend/api/s3.py
> +        return None
Should this be returning `[]`?

2023-02-01 04:27 UTC, richaagarwal commented
@klai95 I haven't had a chance to review the code in this PR but wanted to ask for a couple broader changes:
- It will be helpful to add a PR description (ideally before review starts next time). In addition to linking to an existing issue(s), it is also helpful to provide a summary of the code changes introduced, which can help guide the reviewer 
- Though we are squashing upon merge, I would still recommend descriptive commit messages. You can amend commits as necessary in this case, and possibly consolidate some of them so each commit represents a meaningful change

2023-02-01 06:07 UTC, klai95 commented
> @klai95 I haven't had a chance to review the code in this PR but wanted to ask for a couple broader changes:
> 
> * It will be helpful to add a PR description (ideally before review starts next time). In addition to linking to any existing issue(s), it is also helpful to provide a summary of the code changes introduced, which can help guide the reviewer
> * Though we are squashing upon merge, I would still recommend descriptive commit messages. You can amend commits as necessary in this case, and possibly consolidate some of them so each commit represents a meaningful change

I have added information in the description of the PR just now, and will be making sure I use descriptive commit messages every-time, as currently sometimes I do and sometimes I don't. Let me know if there is any further context I can provide. The PR is currently fully functional.

2023-02-01 21:53 UTC, manasaV3 commented on backend/api/model.py
> +        GROUP BY 1,2
Actually, in install data, we fetch the entire data and not just the last year's data.

2023-02-01 22:04 UTC, manasaV3 requested changes

2023-02-01 22:04 UTC, manasaV3 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/commit_activity.json").get(plugin)
As mentioned in [this comment](https://github.com/chanzuckerberg/napari-hub/pull/849#discussion_r1092489726), we should return `[]` in case there is no match. 
```
return _load_json_from_s3("activity_dashboard_data/commit_activity.json").get(plugin, [])
```

2023-02-01 23:42 UTC, manasaV3 requested changes

2023-02-01 23:42 UTC, manasaV3 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/latest_commits.json").get(plugin, [])
Why is this defaulting to `[]`?

2023-02-01 23:42 UTC, manasaV3 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/total_commits.json").get(plugin, [])
Why is this defaulting to `[]`?

2023-02-01 23:51 UTC, klai95 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/latest_commits.json").get(plugin, [])
I was thinking the same logic would apply for the other files to return [] in case there is no match. Correct me if I am wrong though.

2023-02-01 23:51 UTC, klai95 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/total_commits.json").get(plugin, [])
I was thinking the same logic would apply for the other files to return [] in case there is no match. Correct me if I am wrong though.

2023-02-02 00:28 UTC, manasaV3 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/latest_commits.json").get(plugin, [])
We were returning `[]` in the case of `get_commit_activity` because it is expected to return a list of commit_activity timelines. When there is no match, we return the default fallback of an empty list.  
But for the other two, we can return `null` as the default value. Their response type should never be a `list`.

2023-02-02 00:29 UTC, manasaV3 commented on backend/api/s3.py
> +def get_commit_activity(plugin: str) -> Any:
Can we update the return type to be `List`?

2023-02-02 00:34 UTC, klai95 commented on backend/api/s3.py
> +    return _load_json_from_s3("activity_dashboard_data/latest_commits.json").get(plugin, [])
Got it, thanks for clarifying!

2023-02-02 00:36 UTC, klai95 commented on backend/api/s3.py
> +def get_commit_activity(plugin: str) -> Any:
Changed it!

2023-02-02 01:03 UTC, manasaV3 approved these changes

2023-02-02 01:06 UTC, merged