ensure python versions are sorted
chanzuckerberg/napari-hub pull request #86
Opened 2021-06-16 21:09 UTC by 0x00b1

We may want to add a build step to automatically populate `SUPPORTED_PYTHON_VERSIONS`. 

We will need to provide a custom comparison function if we want to non-uniform version numbers (e.g. `3` and `3.9.5`).

2021-06-16 21:11 UTC, 0x00b1 commented
Could someone link the issue? I want to reproduce to ensure the issue is actually fixed. 😆

2021-06-16 21:56 UTC, codemonkey800 commented
@0x00b1 I think the order is messed up because we're using [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) in the React component. The array `SUPPORTED_PYTHON_VERSIONS` is technically already sorted, but the result of `Object.entries()` is not guaranteed:

https://github.com/chanzuckerberg/napari-hub/blob/75e867e90878e48cec4b2d0382cb8c9acfa76e17/client/src/components/PluginSearch/PluginFilterByForm.tsx#L67-L74

2021-06-16 22:05 UTC, justinelarsen approved these changes
Nice! Thanks for fixing :)

2021-06-24 20:02 UTC, justinelarsen requested changes
@0x00b1  This PR needs some work. See @codemonkey800 's comment https://github.com/chanzuckerberg/napari-hub/pull/86#issuecomment-862754679

2021-06-29 04:02 UTC, neuromusic commented
hey @0x00b1 do you think you can land this or should @codemonkey800 or @kne42 pick it up?

2021-08-16 21:54 UTC, klai95 commented
Previous Behavior:
The order of the array returned by Object.entries() does not depend on how the object is defined.
Current Behavior:
The ordering of the properties is the same as that given by looping over the property values of the object manually.

PR Updating the Docs:
https://github.com/mdn/content/pull/6937

2021-08-16 22:11 UTC, closed without merging