Update frontend API contract
chanzuckerberg/napari-hub pull request #865
Opened 2023-01-30 19:37 UTC by codemonkey800

## Description

- Updates typing and hooks for fetching metrics data to match new API contract
- Renames `@/types/stats` -> `@/types/metrics`
- Adds data validation for metrics API response

2023-01-30 20:34 UTC, manasaV3 requested changes

2023-01-30 20:34 UTC, manasaV3 commented on frontend/src/components/ActivityDashboard/ActivityUsageSection/RecentInstalls.tsx
> -      count={stats?.installsInLast30Days}
This should `installs_in_last_30_days`

2023-01-30 20:34 UTC, manasaV3 commented on frontend/src/components/ActivityDashboard/ActivityUsageSection/TotalInstalls.tsx
> -      count={stats?.totalInstalls}
This should be `.total_installs`

2023-01-30 20:59 UTC, klai95 commented on frontend/src/components/ActivityDashboard/ActivityDashboard.tsx
> +    const { timeline, stats } = metrics.usage;
A related question: where would we include `metrics.maintenance` that the backend PRs have?

2023-01-31 00:19 UTC, klai95 commented on frontend/src/utils/validate/validateMetricsData.ts
> +    installs_in_last_30_days: z.number(),
More of a heads-up than a review: if I make any changes to the name of the fields in my backend PRs, I will let you know to ensure frontend and backend abide by the same API contract

2023-02-02 20:50 UTC, manasaV3 approved these changes

2023-02-03 18:24 UTC, merged