Add pull request template
chanzuckerberg/napari-hub pull request #870
Opened 2023-01-30 22:09 UTC by codemonkey800

## Description

Closes #841 

Adds PR template for all PRs to the hub.

## Demos

<img width="922" alt="image" src="https://user-images.githubusercontent.com/2176050/215628261-daddd515-7343-4ef7-9ab4-404b03b26c43.png">

2023-01-30 22:35 UTC, manasaV3 approved these changes

2023-01-30 22:39 UTC, klai95 approved these changes

2023-01-30 22:58 UTC, richaagarwal approved these changes

2023-01-30 22:59 UTC, richaagarwal requested changes
Ack sorry, approved but then just realized - we want to ensure we don't automatically close tickets from merging into staging, since we have a new column "Pending QA & Release", so I'd edit that section

2023-01-30 23:00 UTC, richaagarwal commented on .github/pull_request_template.md
> +If this PR closes an issue, add closing keywords and link the issues so it's
See this comment - https://github.com/chanzuckerberg/napari-hub/pull/870#pullrequestreview-1276160661

I wonder if we could suggest language such as "Addresses #ticket" to link them but not close automatically, but curious what your thoughts are.

2023-01-31 01:09 UTC, richaagarwal approved these changes

2023-01-31 01:10 UTC, richaagarwal commented on .github/pull_request_template.md
> +If this PR closes an issue, add closing keywords and link the issues so it's
sounds good, thanks! I think we can still link to the ticket too

2023-01-31 16:58 UTC, merged