Create maintenance activity ETL workflow
chanzuckerberg/napari-hub pull request #939
Opened 2023-03-10 21:23 UTC by klai95

Issue: https://github.com/chanzuckerberg/napari-hub/issues/922
Reference: https://github.com/chanzuckerberg/napari-hub/pull/926
Description: Update the data workflow lambda's existing activity ETL.

2023-03-10 21:29 UTC, richaagarwal commented on data-workflows/activity/model.py
> +class MaintenanceActivity(Model):
I know this still in draft mode, but just wanted to provide some early feedback: Let's try to be consistent with naming, I know we are calling this table GitHub Activity here - https://github.com/chanzuckerberg/napari-hub/pull/927/files.

2023-03-10 21:30 UTC, richaagarwal commented on data-workflows/activity/model.py
> +        table_name = f'{prefix}-install-activity'
Table name should be updated here

2023-04-04 00:46 UTC, klai95 commented
I ran the maintenance activity ETL workflow and wrote the data to the `dev-test-github-activity` for testing purposes. The contents of the table can be seen here: https://us-west-2.console.aws.amazon.com/dynamodbv2/home?region=us-west-2#item-explorer?table=dev-test-github-activity&maximize=true

2023-04-05 21:39 UTC, richaagarwal commented on data-workflows/activity/snowflake_adapter.py
> +    for plugin, column_1, column_2 in cursor:
Is there a reason you've renamed `timestamp` and `count` to `column_1` and `column_2`?

2023-04-05 22:18 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +    for plugin, column_1, column_2 in cursor:
Yes there is. I have already discussed and aligned this matter with Manasa, but basically the reason is that for the `LATEST` workflow `column_2` contains the timestamp, whereas for the `MONTH` workflow `column_1` contains the timestamp.

If the above change was not made, I would be assigning `activity['count']` as the latest commit timestamp value, which would be very confusing. Therefore, that is why I have renamed `timestamp` and `count` more generally. 

For further context, `get_query_projection` in `data-workflows/activity/github_activity_model.py` shows the different query projections returned depending on `GitHubActivityType`. We can see that `column_2` of `GitHubActivityType.LATEST` contains latest commit as timestamp value, but `column_2` of of `GitHubActivityType.TOTAL` contains num_commits as numerical value.

2023-04-06 07:31 UTC, richaagarwal commented on data-workflows/activity/snowflake_adapter.py
> +    for plugin, column_1, column_2 in cursor:
I may be missing something, but wouldn't it be possible to reverse the ordering of the fields in this line https://github.com/chanzuckerberg/napari-hub/pull/939/files#diff-428b7b3e68dae07e5b5d9a5bc45651fd070646d4f2ebb25b13db4a4ae6bbcb84R38 so that we don't have to make changes to the naming here?

2023-04-06 07:54 UTC, richaagarwal commented on data-workflows/activity/github_activity_model.py
> +            return '1, to_timestamp(max(commit_author_date)) as latest_commit'
In addition to my comment regarding the ordering of these fields, I'm wondering why we're saving `1` as the number of commits when the metric is for latest commit. I don't think we need to set the commit count at all, as it's not relevant to the metric, and makes reviewing the data a little more confusing than it needs to be.

2023-04-06 08:09 UTC, manasaV3 requested changes

2023-04-06 08:09 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +                commit_count = activity['column_1']
From [here](https://github.com/chanzuckerberg/napari-hub/pull/939/files#diff-428b7b3e68dae07e5b5d9a5bc45651fd070646d4f2ebb25b13db4a4ae6bbcb84R37-R38), we can see that the value of the `column_1` is always going to be `1`.  
How do we benefit from storing that in the database for the `LATEST` record?

2023-04-06 08:09 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +                timestamp = date_to_utc_timestamp_in_millis(activity['column_1'])
Are we certain the object being returned here is not a datetime object as well?

2023-04-06 08:09 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +    processed_public_plugins = {k.lower(): k for k, v in public_plugins.items()}
Can you please explain why we are doing this? Also, how are we accounting for the hidden plugins?

2023-04-06 08:19 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +            plugin_name = repo_name.split('/')[1]
These are some of the plugins where the name doesn't match the repo name: `'misic-napari', 'napari-denoiseg', 'napari-lattice', 'napari-time-series-plotter', 'iacs-ipac-reader', 'napari-plot', 'napari-stl-exporter', 'napari-cellseg3d', 'napari-pyclesperanto-assistant', 'napari-nucleaizer', 'napari-PICASSO', 'napari-arboretum', 'morphospaces', 'napari-svetlana', 'napari_video', 'elastix-napari', 'recOrder-napari', 'koopa-viz', 'napari-PHILOW', 'napari-mrcfile-handler'`

2023-04-06 08:31 UTC, richaagarwal commented on data-workflows/activity/snowflake_adapter.py
> +    for plugin, column_1, column_2 in cursor:
Also, if the above suggestion does not resolve it, or there's a scenario where we need to add additional fields, we should consider having specific functions for install vs github activity, as I think the variable naming here is important and we don't need to force this function to be extensible.

2023-04-06 19:17 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +    repo = UnicodeAttribute(null=True)
Repo values should never be null, since `imaging.github.commits` have non-null values for repo

2023-04-06 21:39 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +from backend.api.model import get_public_plugins, get_excluded_plugins
To resolve this, we can create a plugin module, which temporarily returns results by replicating the functionality of reading data from s3.

2023-04-06 21:51 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +    processed_public_plugins = {k.lower(): k for k, v in public_plugins.items()}
We should be using logic referenced here: https://github.com/chanzuckerberg/napari-hub/blob/main/backend/api/model.py#L483

2023-04-06 22:01 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +    processed_public_plugins = {k.lower(): k for k, v in public_plugins.items()}
Note to self for changes: create a module that contains logic just like `_get_repo_to_plugin_dict()` in `data-workflows` for this lambda

2023-04-06 22:59 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +             for name, ts in plugins_by_formatted_timestamp.items()])
Just want to clarify, the suggested change should be the below right?
```
subquery = ' OR '.join( [f"LOWER(repo) = '{name}' AND to_timestamp(commit_author_date) >= "f"{TIMESTAMP_FORMAT.format(ts.replace(day=1))}" for name, ts in plugins_by_earliest_ts.items()])

2023-04-06 23:03 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +             for name, ts in plugins_by_formatted_timestamp.items()])
Good catch.. yes..

2023-04-07 01:22 UTC, klai95 commented
Verified that the changes are working as expected

![Screenshot 2023-04-06 at 8 21 20 PM](https://user-images.githubusercontent.com/70177777/230521310-1addf507-9ac1-4c92-bce6-41502adf6bd4.png)

2023-04-07 20:21 UTC, manasaV3 requested changes

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/plugin/s3.py
> +    index_json = get_index()
Instead of having a get_index method, what are your thoughts on directly calling the get_cache, like below:

```
index_json = _get_cache('cache/index.json')
```

The get_cache handles only one use cases compared to the varied usecases it handles in the source where we duplicated it from. So, it can directly return an empty dictionary. 
```
def _get_cache(key: str) -> Dict:
    try:
        bucket = os.getenv('BUCKET')
        bucket_path = os.getenv('BUCKET_PATH', '')
        s3_client = boto3.client("s3")
        return json.loads(s3_client.get_object(Bucket=bucket, Key=os.path.join(bucket_path, key))['Body'].read())
    except ClientError:
        ....
        return {}
```

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/plugin/s3.py
> +            repo_to_plugin_dict[plugin_obj['code_repository'].replace('https://github.com/', '')] = plugin_obj['name']
Can we simplify this to:
```
code_repository = plugin_obj.get('code_repository')
if code_repository:
    repo_to_plugin_dict[code_repository.replace('https://github.com/', '')] = plugin_obj['name']
```

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +                repo AS name, DATE_TRUNC('DAY', TO_DATE(min(commit_author_date))) AS earliest_timestamp
Do we need the `TO_DATE(..)` on the `min(commit_author_date)`?

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +            ORDER BY repo
This needs to be updated in accordance with the projection.

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +                LOWER(file_project) AS name, DATE_TRUNC('DAY', MIN(timestamp)) AS earliest_timestamp
I believe this was missed in the existing code as well, we should update the group_by, and order_by to use the `name` not `file_project`.

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +        accumulator_updater = _cursor_to_plugin_github_activity_total_mapper
This is nice. Definitely, something that we should consider incorporating for Install Activity as well in the future. 

What are your thoughts on having the accumulator_updater be a part of the GitHubActivityType enum, so we could fetch it as `github_activity_type.get_accumulator_updater()`?

2023-04-07 20:21 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +    return accumulator
I believe this and [_cursor_to_plugin_install_activity_mapper](https://github.com/chanzuckerberg/napari-hub/pull/939/files#diff-7380baa5c51177f0c5a8b84b254b7b5116c998a300a601840a67f38e780bc48cR132) are doing the exact same this.

2023-04-07 22:11 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +                repo AS name, DATE_TRUNC('DAY', TO_DATE(min(commit_author_date))) AS earliest_timestamp
Yes. `Function DATE_TRUNC does not support VARCHAR(16777216) argument type` is displayed when `TO_DATE(...)` is not used.

2023-04-07 22:17 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +        accumulator_updater = _cursor_to_plugin_github_activity_total_mapper
I think that is a good idea!

2023-04-07 22:22 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +    return accumulator
They are very similar, but they are different in that `_cursor_to_plugin_install_activity_mapper` contains the field`plugin` while `_cursor_to_plugin_github_activity_month_mapper` contains the field `repo`

2023-04-07 23:30 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +                LOWER(file_project) AS name, DATE_TRUNC('DAY', MIN(timestamp)) AS earliest_timestamp
updated!

2023-04-07 23:32 UTC, klai95 commented
Verified the code changes after review feedback are working as expected and the screenshot below matches the schema requirements of the ticket: https://github.com/chanzuckerberg/napari-hub/issues/922
<img width="1124" alt="Screenshot 2023-04-07 at 6 32 32 PM" src="https://user-images.githubusercontent.com/70177777/230692072-46298be5-7508-4ea8-9d07-435bc02a5cee.png">

2023-04-07 23:49 UTC, klai95 commented on data-workflows/tests/test_handler.py
> +        handle({'Records': [{'body': '{"type":"install_activity"}'}, {'body': '{"type":"bar"}'}]}, None)
Because as of right now `test_handle_valid_activity_event` should only be testing `install_acitvity`. The way the code was structured before in `handler.py`, `_update_activity()` calls both `update_install_activity` and `update_github_activity`, which leads to the error provided in the screenshot below. 

<img width="1031" alt="Screenshot 2023-04-07 at 6 41 18 PM" src="https://user-images.githubusercontent.com/70177777/230692563-d78246ca-fb07-4979-bebc-c3c7bd2aa7fd.png">
GitHub Action: https://github.com/chanzuckerberg/napari-hub/actions/runs/4642105826/jobs/8215690608?pr=939

In contrast, this is the screenshot after the code changes have been implemented.
<img width="1364" alt="Screenshot 2023-04-07 at 6 48 27 PM" src="https://user-images.githubusercontent.com/70177777/230692951-c38cf38d-c48b-4322-ad23-6d02d480c79e.png">
Note that the error in `TestHandle.test_handle_valid_activity_event` no longer appears.
GitHub Action: https://github.com/chanzuckerberg/napari-hub/actions/runs/4642173319/jobs/8215810116?pr=939

@manasaV3

2023-04-10 16:58 UTC, klai95 commented
I have verified the changes after code review feedback are working as expected and the screenshot below matches the schema requirements of the ticket: https://github.com/chanzuckerberg/napari-hub/issues/922. Note that the current implementation adds commit data for hidden plugins as well on top of public plugins. As can be seen in the screenshot below, the table includes data for the `napari-threedee` plugin. 

<img width="1096" alt="Screenshot 2023-04-10 at 11 54 09 AM" src="https://user-images.githubusercontent.com/70177777/230950812-e86e6841-7e39-4414-ba6a-80a7191deecd.png">

2023-04-10 17:07 UTC, klai95 commented
The current `failing check` error does not have anything to do with the code changes introduced in this PR, as verified with @manasaV3. She will have a fix out for this issue shortly.

2023-04-10 18:47 UTC, manasaV3 commented
Wanted to make a call out, since the data has to be backfilled for github activity since the beginning of time, the `last_updated_timestamp` in the parameter store should be reset to the beginning of time.

2023-04-10 22:50 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +            plugin_name = repo_name.split('/')[1]
The updated implementation takes care of this case

2023-04-10 22:50 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +                timestamp = date_to_utc_timestamp_in_millis(activity['column_1'])
Yes

2023-04-11 18:12 UTC, kne42 approved these changes
LGTM. a few style requests. also i find it weird that in some places you use `Dict`/`List` from the `typing` library as annotations in certain places but use the built-in types elsewhere, sometimes mismatching them (e.g. i saw a `dict[str, List]`)

2023-04-11 18:12 UTC, kne42 commented on data-workflows/plugin/helpers.py
> +        if 'themes' in manifest_contributions and manifest_contributions['themes']:
```suggestion
        if manifest_contributions.get('themes'):
```

and similar down the chain

2023-04-11 18:12 UTC, kne42 commented on data-workflows/plugin/helpers.py
> +            manifest_attributes['plugin_types'].append('theme')
you reuse `manifest_attributes['plugin_types']` a lot, i would put it in a variable

2023-04-11 18:20 UTC, klai95 commented
> LGTM. a few style requests. also i find it weird that in some places you use `Dict`/`List` from the `typing` library as annotations in certain places but use the built-in types elsewhere, sometimes mismatching them (e.g. i saw a `dict[str, List]`)

Methods in `helps.py` are basically copied over from `model.py` under the `backend` folder because the `data-workflow` lambda will not have access to the methods in `model.py` at runtime. That being said, I do agree that it needs refactoring, but just calling out that we would need to make modifications in `model.py` as well, since that is where the code is coming from.

2023-04-11 18:27 UTC, richaagarwal requested changes
@klai95 I saw a comment regarding the need to duplicate methods from `model.py` into `helpers.py`.  We should not be doing this.  Please make any changes/refactors necessary to avoid significant duplication of methods.

2023-04-11 18:29 UTC, klai95 commented
> @klai95 I saw a comment regarding the need to duplicate methods from `model.py` into `helpers.py`. We should not be doing this. Please make any changes/refactors necessary to avoid significant duplication of methods.

As I have mentioned here https://github.com/chanzuckerberg/napari-hub/pull/939#issuecomment-1503877855, the reason is that the `data-workflow` lambda does not have access to methods such as `get_plugin`, etc provided in backend/model.py at runtime. This is something I have also discussed with @manasaV3 about.

2023-04-11 18:39 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +from backend.api.model import get_public_plugins, get_excluded_plugins
@richaagarwal

2023-04-11 19:46 UTC, klai95 commented
> Since the data has to be backfilled for github activity since the beginning of time, the `last_updated_timestamp` in the parameter store should be reset to the beginning of time for each environment to get the complete data.

Note to self: go to [/prod/napari-hub/data-workflows/config](https://us-west-2.console.aws.amazon.com/systems-manager/parameters/prod/napari-hub/data-workflows/config/description?region=us-west-2&tab=Table) and reset `last_activity_fetched_timestamp` to the beginning of time; do this for all environments

2023-04-11 20:28 UTC, manasaV3 commented
> > Since the data has to be backfilled for github activity since the beginning of time, the `last_updated_timestamp` in the parameter store should be reset to the beginning of time for each environment to get the complete data.
> 
> Note to self: go to [/prod/napari-hub/data-workflows/config](https://us-west-2.console.aws.amazon.com/systems-manager/parameters/prod/napari-hub/data-workflows/config/description?region=us-west-2&tab=Table) and reset `last_activity_fetched_timestamp` to the beginning of time (0); do this for all environments

You only need to set it to {'last_activity_fetched_timestamp': 0}

2023-04-11 20:29 UTC, manasaV3 commented on .happy/terraform/modules/ecs-stack/main.tf
> +    "BUCKET_PATH" = var.env == "dev" ? local.custom_stack_name : ""
Nit: Spacing

2023-04-11 20:29 UTC, manasaV3 commented on .happy/terraform/modules/ecs-stack/main.tf
> +      "s3:PutObject",
We should not need the `s3:PutObject` permission. We only need the `s3:GetObject` for data-workflows.

2023-04-12 00:07 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +                                  repo=repo)
I believe this be simplified to:
```
timestamp = activity.get('timestamp')
commit_count = activity.get('count')
item = GitHubActivity(plugin_name,
                                  activity_type.format_to_type_identifier(repo, timestamp),
                                  granularity=activity_type.name,
                                  timestamp=activity_type.format_to_timestamp(timestamp),
                                  commit_count=commit_count,
                                  repo=repo)
```
We can leverage the `format_to_timestamp()` method, which was defined to be used just here.

2023-04-12 00:07 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +            continue
Nit: While this code is functionally correct, it feels weird to assign a value only in the if block and use it in other places. What are your thoughts on formatting it to:
```
plugin_name = repo_to_plugin_dict.get(repo)
if not plugin_name:
    continue 
```

2023-04-12 00:12 UTC, manasaV3 commented on data-workflows/activity/github_activity_model.py
> +        import activity.snowflake_adapter as sf
It feels like it was done to avoid a circular dependency. This check could be a part of snowflake_adapter [here](https://github.com/chanzuckerberg/napari-hub/pull/939/files#diff-7380baa5c51177f0c5a8b84b254b7b5116c998a300a601840a67f38e780bc48cR34).

2023-04-12 00:24 UTC, manasaV3 requested changes

2023-04-12 00:24 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +            ORDER BY plugin, timestamp
Nice clean up magic. ✨

2023-04-12 00:24 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +    )
This is very clean and easy to understand. 🔥

2023-04-12 00:24 UTC, manasaV3 commented on data-workflows/activity/snowflake_adapter.py
> +    return accumulator
Could the name of the projection be changed to a common term if that would allow us to reuse the method?

2023-04-12 00:24 UTC, manasaV3 commented on data-workflows/handler.py
> +    return last_updated_timestamp, current_timestamp
BLOCKER: Wouldn't this update the parameter store with current_timestamp even if the workflow fails?

2023-04-12 00:24 UTC, manasaV3 commented on data-workflows/handler.py
> +            _update_github_activity()
BLOCKER: This will break the workflow.

2023-04-12 00:24 UTC, manasaV3 commented on data-workflows/handler.py
> +    activity.processor.update_github_activity(last_updated_timestamp, current_timestamp)
BLOCKER: We are updating the same timestamp in two different workflows.

2023-04-12 19:08 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +    return accumulator
Yes. Similar to how we have renamed `plugin` & `repo` to `name` in the SQL queries, we can make the same change here. As a result, we can rename  `_cursor_to_plugin_install_activity_mapper` to `_cursor_to_plugin_activity_mapper`, and get rid of `_cursor_to_plugin_github_activity_month_mapper`

2023-04-13 17:45 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +        return github_activity_type
In this case, I believe we are using `__new__` to customize the creation process of `GitHubActivityType` instances by setting additional attributes (`timestamp_formatter` and `type_identifier_formatter`) on the object before it is returned as the new instance, and it  allows the `GitHubActivityType` instances to have these additional attributes immediately upon creation, without needing to set them in the `__init__` method.

2023-04-14 19:02 UTC, kne42 commented on data-workflows/activity/snowflake_adapter.py
> +    if github_activity_type.name == 'LATEST':
these are enums so i would be comparing them directly instead of by their names

2023-04-14 19:02 UTC, kne42 commented on data-workflows/activity/snowflake_adapter.py
> +    :param SnowflakeCursor cursor:
what's this?

2023-04-14 19:53 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +    :param SnowflakeCursor cursor:
it is the accumulator updater method used by `get_plugins_install_count_since_timestamp` for `install activity` and `get_plugins_commit_count_since_timestamp` for `github-activity-LATEST`. The reason both are being used by this method is that they have the exact code in their methods.

Previously, I had separated out `_cursor_to_plugin_activity_mapper` into the two corresponding methods for `install activity` and for `github-activity-LATEST`, but I have since refactored the code to avoid duplication.

If you think there is a name for the method that captures it better, please do let me know! Thanks!

2023-04-14 20:33 UTC, klai95 commented on data-workflows/activity/snowflake_adapter.py
> +    if github_activity_type.name == 'LATEST':
Feedback has been addressed!

2023-04-14 20:33 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +                     other.commit_count, other.repo))
Feedback has been addressed!

2023-04-14 20:33 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +        return 'repo AS name, count(*) as commit_count'
Feedback has been addressed!

2023-04-14 20:35 UTC, klai95 commented on data-workflows/activity/github_activity_model.py
> +        return 'name'
Feedback has been addressed! As a result, the methods `query_projection` and `query_sorting` are no longer needed

2023-04-14 20:45 UTC, kne42 submitted a review, later dismissed
Lots cleaner thanks!

2023-04-24 22:50 UTC, kne42 approved these changes
some nits, otherwise lgtm

2023-04-24 22:50 UTC, kne42 commented on data-workflows/activity/github_activity_model.py
> +    """
```suggestion
    """Transforms plugin commit data generated by get_plugins_commit_count_since_timestamp to the expected format
    and then writes the formatted data to the corresponding github-activity dynamo table in each environment

    :param dict[str, list] data: plugin commit data of type dictionary in which the key is plugin name
    of type str and the value is Github activities of type list
    :param GitHubActivityType activity_type:
    """
```

2023-04-24 22:50 UTC, kne42 commented on data-workflows/activity/snowflake_adapter.py
> +    """
```suggestion
    """This method gets the commit data since a specific starting point for each plugin.

    If GitHubActivityType.LATEST, fetch the latest commit timestamp, so construct query without commit count constraint
    If GitHubActivityType.MONTH, fetch the sum of commits from the beginning of the month of the timestamp specified
    for each of the plugin.
    If GitHubActivityType.TOTAL, fetch the sum of commits over all time, so construct query without timestamp constraint

    :param dict[str, datetime] plugins_by_earliest_ts: plugin name by earliest timestamp of commit record added
    :param GitHubActivityType github_activity_type:
    """
```

2023-04-26 18:22 UTC, merged