Script for seeding category data from S3
chanzuckerberg/napari-hub pull request #959
Opened 2023-03-22 00:58 UTC by codemonkey800

## Description

#866

Depends on https://github.com/chanzuckerberg/napari-hub/pull/986

This PR adds a script for seeding category data from the S3 bucket. This works by adding a general purpose `run_workflow.py` script that can be run manually to run a particular workflow from CLI, or by importing the `run_workflow()` function. This will allow us to run the same scripts in our workflows locally and from the data-workflows lambda.

To seed category data from S3, run the `run_workflow.py` script:

```sh
AWS_PROFILE=sci-imaging \
  BUCKET=<bucket> \
  STACK_NAME=<stack-name>
  python run_workflow.py seed-s3-categories \
  --edam-version EDAM-BIOIMAGING:alpha06 \
  --s3_path category/EDAM-BIOIMAGING/alpha06.json
```

For example, this is the command I used for testing:

```sh
AWS_PROFILE=sci-imaging \
  BUCKET=napari-hub-dev \
  STACK_NAME=dev-test-cat \
  python run_workflow.py seed-s3-categories \
  --edam-version EDAM-BIOIMAGING:alpha06 \
  --s3_path category/EDAM-BIOIMAGING/alpha06.json
```

The workflow can also be run from Python using:

```py
from run_workflow import run_workflow

run_workflow({
    'type': 'seed-s3-categories',
    'edam_version': 'EDAM-BIOIMAGING:alpha06',
    's3_path': 'category/EDAM-BIOIMAGING/alpha06.json',
})
```

## Demos

List of first 50 categories in Dynamo

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/2176050/226774579-86fe0926-7b44-4213-b773-b40bed9979cd.png">

2023-03-27 17:31 UTC, manasaV3 reviewed
Really cool stuff..  🎉

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/run_workflow.py
> +        )
For consistency, does it make sense to trigger this from the handler?

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/categories.py
> +    h = hashlib.new('md5')
Nit: Could we rename this variable

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/categories.py
> +    print(f'Seeding category data from S3 version={edam_version} bucket={bucket} table={table}')
Nit: We could use logger here.

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/categories.py
> +    s3_path = f'category/{edam_name}/{version}.json'
We could be getting this as a complete path from the input data. That would allow us also specify paths of different formats.

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/categories.py
> +    class CategoryModel(Model):
I believe this is inside a method because the table is passed a parameter. 

Because the category table name is always going to follow the format `<stack_name>-category`, what are your thoughts on fetching the prefix from the env variables, and appending it to a hard-coded category table name?

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/categories.py
> +    label = category.get('label', '')
Just curious, did we ever encounter a case where we didn't have a label or hierarchy?

2023-03-27 17:31 UTC, manasaV3 commented on data-workflows/categories.py
> +    client = S3Client(bucket)
We should also pass prefix here. 

As the bucket we are fetching from will depend on the env, what are your thoughts on getting the bucket and prefix from env variables?

2023-03-30 17:15 UTC, manasaV3 commented on data-workflows/categories.py
> +    client = S3Client(bucket)
Could we please delete the picture that exposes the snowflake username, password?

2023-03-30 17:35 UTC, klai95 submitted a review, later dismissed

2023-03-31 00:00 UTC, manasaV3 commented on data-workflows/categories.py
> +    client = S3Client(bucket)
> thinking about it more, I think what I need to do is first check if STACK_NAME == 'prod or STACK_NAME == 'staging, otherwise pass STACK_NAME as the bucket prefix

As the lambda will only have permissions from the s3 bucket in its environment, I think it makes sense to pass the bucket name as an env variable too. 
In the backend, we have a similar use case. To handle that, we set the bucket prefix env in terraform only for dev. 
Code Ref: https://github.com/chanzuckerberg/napari-hub/blob/main/.happy/terraform/modules/ecs-stack/main.tf#L179

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/activity/update_activity.py
> +def update_activity() -> None:
I believe this file got added incorrectly during a rebase.

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/categories.py
> +def run_seed_s3_categories_workflow(edam_version: str, s3_path: str):
Nit: Not sure, if the versioning would always be an Edam version.

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/utils/env.py
> +    value = os.environ.get(key)
Nit: In most places, we currently use the `os.getenv(..)`, a wrapper around the `os.environ`. It should also return `None` if the value doesn't exist.

The only reason I'd recommend using `os.getenv` over this is consistency. What are your thoughts on that?

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/utils/env.py
> +    """
Could we update the documentation to use sphinx styling? 
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/utils/env.py
> +def get_required_env(key: str) -> str:
Really cool idea. 😀

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/utils/s3.py
> +        obj = self._client.get_object(
Can we add a timing log around this s3 call?

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/handler.py
> +        payload = json.loads(record.get("body"))
We still need the existing check on the `event_type`. We would call the run_workflow, if `event_type == 'category'`

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/categories.py
> +        prefix="" if STACK_NAME in ("prod", "staging") else STACK_NAME,
What are your thoughts on doing it similar to: https://github.com/chanzuckerberg/napari-hub/blob/main/.happy/terraform/modules/ecs-stack/main.tf#L179 ?

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/categories.py
> +        f"s3_path={s3_path} bucket={bucket} table={CategoryModel.Meta.table_name}"
Can we also add prefix to the logged data, please.

2023-03-31 00:27 UTC, manasaV3 commented on data-workflows/categories.py
> +STACK_NAME = get_required_env("STACK_NAME")
Just a heads up, if this gets assigned here, you might have to set up mocks for this wherever this module gets imported.

2023-04-04 01:46 UTC, klai95 commented on data-workflows/run_workflow.py
> +def run_workflow(event: Dict):
Nicely done! Having this workflow is super helpful for the future!

2023-04-04 02:00 UTC, klai95 submitted a review, later dismissed

2023-04-06 22:54 UTC, manasaV3 commented on data-workflows/utils/time.py
> +    print(f"{message} duration={duration}ms")
Can we make this a log statement?

2023-04-06 22:54 UTC, manasaV3 commented on data-workflows/categories.py
> +        table_name = f"{STACK_NAME}-category"
Can we also add host for local dynamo?

2023-04-06 22:54 UTC, manasaV3 commented on data-workflows/categories.py
> +    bucket = get_required_env("BUCKET")
We should add this to the env variables of the lambda.

2023-04-06 22:54 UTC, manasaV3 commented on data-workflows/categories.py
> +    env = get_required_env("ENV")
I believe we use the `env` only for determining the s3 prefix. What are your thoughts on having the s3_prefix also be an environment variable so that the workflow is environment agnostic?

2023-04-06 22:54 UTC, manasaV3 commented on data-workflows/handler.py
> +                return
🔥

2023-04-07 06:58 UTC, klai95 commented on data-workflows/categories.py
> +        table_name = f"{STACK_NAME}-category"
As Manasa has mentioned, we would add another line of code
```
host = os.getenv('LOCAL_DYNAMO_HOST')

2023-04-11 20:01 UTC, manasaV3 commented
I believe we were holding off on incorporating changes from https://github.com/chanzuckerberg/napari-hub/pull/986 until Kevin's ETL PR was merged, to avoid conflicts that might be harder to resolve on his end.

2023-04-11 20:22 UTC, manasaV3 commented on data-workflows/handler.py
> +            s3_prefix = event.get("s3_prefix")
This should come from the `os.getenv` for consistency.

2023-04-11 20:22 UTC, manasaV3 commented on .happy/terraform/modules/ecs-stack/main.tf
> +    "ENV"                = var.env
We don't use the ENV environment variable anywhere. I think this got added instead of [this](https://github.com/chanzuckerberg/napari-hub/blob/56e863b93414dff3e57aa8cf7d98b6c5a5ea917f/.happy/terraform/modules/ecs-stack/main.tf#L178-L179).

2023-04-11 20:47 UTC, klai95 commented on data-workflows/handler.py
> +        if event_type == "seed-s3-categories":
I think `elif` is a good callout.

2023-04-26 20:34 UTC, klai95 commented on data-workflows/handler.py
> +        # TODO: Create a dict for event_type by method to be called
Is this comment still needed?

2023-04-26 20:42 UTC, klai95 commented on data-workflows/activity/processor.py
> +def _fetch_data_and_write_to_dynamo(data: dict[str, datetime], install_activity_type: InstallActivityType) -> None:
I think adding docstring in this method to detail exactly what data is would be helpful. It can also help clarify why it is being passed in `get_plugins_install_count_since_timestamp`

2023-04-26 20:44 UTC, klai95 commented on data-workflows/categories.py
> +    dimension = category.get("dimension")
Is there a reason why `dimension` does not have a default value?

2023-05-02 18:46 UTC, manasaV3 requested changes

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/run_workflow.py
> +    seed_s3_categories_parser.add_argument("--s3-prefix", default="")
Looking at this [snippet](https://github.com/chanzuckerberg/napari-hub/pull/959/files#diff-48bc4f460db59d31cd383f878f7ec7cb346afc564703a5025e6b180fe6070f93R56), we get the bucket and the path from os, variable and not from the event.  So, we would only need to fetch `version` and `s3-path` here.

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/run_workflow.py
> +    handler.handle({"Records": [{"body": json.dumps(event)}]}, {})
I recall we had landed on this as an approach earlier. But, with how modular the current categories file  now is we could simply call it as follows:
```
categories.run_seed_s3_categories_workflow(event.get("version"), event.get("s3_path"))
```

This would be similar to how we would call it in the handler. 

I feel that would reduce the complexity of the above statement and make it more intuitive here.

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/utils/s3.py
> +        try:
Nit: Can we add timing logs here as well?

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/utils/s3.py
> +    def __init__(self, bucket: str, prefix=""):
Nit: prefix also needs typing.

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/utils/s3.py
> +    def _get_from_s3(self, s3_path):
Nit: s3_path needs type

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/categories.py
> +STACK_NAME = os.getenv("STACK_NAME")
Can we add default value for this to be `local` as we now have a default dynamo setup.

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/handler.py
> +    return logger
We could make this a constant so it is consistent with the other implementation. Untested code snippet alert:
```
LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)
```
With that, we would no longer need this method, and the log statements below could leverage this `LOGGER`.

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/tests/test_handler.py
> +
Nit: Extra line?

2023-05-02 18:46 UTC, manasaV3 commented on data-workflows/tests/test_handler.py
>          self._verify(0)
If my memory serves me correctly, I remember there being additional unit tests for the new components that were added, those seem missing currently.

2023-05-02 19:20 UTC, klai95 commented on data-workflows/handler.py
> +            version = event.get("version")
since the parameter types for `version` and `s3_path` are `str`, what are your thoughts on having `version = event.get("version", "")` and `s3_path = event.get("s3_path", "")`?

2023-05-02 19:22 UTC, klai95 commented on data-workflows/run_workflow.py
> +    Function for running a particular data workflow based on the event type. The
It might be helpful to add some detail to the structure/values of the dict in the docstring. What are your thoughts on that?

2023-05-04 04:01 UTC, richaagarwal commented on data-workflows/handler.py
> +            version = event.get("version")
@klai95 Since we require values for these parameters (see this line - https://github.com/chanzuckerberg/napari-hub/pull/959/files#diff-48bc4f460db59d31cd383f878f7ec7cb346afc564703a5025e6b180fe6070f93R62), we would not want to set empty defaults.

2023-05-04 04:05 UTC, richaagarwal commented on data-workflows/categories.py
> +    dimension = category.get("dimension")
Neither of these need a default value. Setting a default value implies that we would sometimes expect missing data and, further, would not want to error out based on that. We control the data source in this case.

2023-05-05 21:11 UTC, manasaV3 reviewed
I believe this is missing unit tests. 😅

2023-05-05 21:11 UTC, manasaV3 commented on data-workflows/handler.py
> +            categories_path = event.get("categories_path ")
There is an extra space after `categories_path`

2023-05-08 17:54 UTC, manasaV3 commented on data-workflows/categories.py
> +    if not all(version, categories_path):
`all` takes an iterable as parameter. So, we should make this `all([version, categories_path])`

2023-05-08 17:58 UTC, manasaV3 submitted a review, later dismissed
Functionality LGTM. But, might require unit test coverage.

2023-05-08 19:39 UTC, manasaV3 commented on data-workflows/activity/update_activity.py
> +def update_activity() -> None:
Sorry, just noticed this. As we are moving this already, would it make sense for this to live in `activity.processor` file? That way we could expose only this method to the handler from that file.

2023-05-08 19:39 UTC, manasaV3 commented on data-workflows/categories.py
> +import os
What do you think about moving this file into a category folder? I think it could help create consistency so all the workflows have their package.

2023-05-09 23:38 UTC, manasaV3 approved these changes
LGTM

2023-05-10 14:41 UTC, merged