Filter maintenance.timeline to return data from expected date range based on limit
chanzuckerberg/napari-hub pull request #960
Opened 2023-03-22 01:14 UTC by klai95

Issue: https://github.com/chanzuckerberg/napari-hub/issues/958

2023-03-22 19:41 UTC, richaagarwal commented on backend/api/model.py
> +    end_date_str = str(end_date)
I see.  But you are converting the timestamp to a `datetime` in line 452, so you could easily convert  it to a `date` instead, e.g. `date.fromtimestamp(item['timestamp'])`, and then compare all 3 dates directly.

I think the code would be much cleaner this way, without having to format the datetimes to strings and doing less conversions overall. What do you think?

2023-03-22 20:40 UTC, klai95 commented on backend/api/model.py
> +    end_date_str = str(end_date)
I agree with this assessment! By doing so, the only conversion we need to do is on line 452, and then we can compare all three `date` objects on line 453 without having to purpose two lines for converting `date` objects to strings

2023-03-25 00:51 UTC, manasaV3 requested changes

2023-03-25 00:51 UTC, manasaV3 commented on backend/api/model.py
> +    end_date_str = str(end_date)
It looks like the `item['timestamp']` is in milliseconds from line 452. 
Converting the start and end date to milliseconds as well would be more optimal here for two reasons. 
1. You no longer have to do the conversion on the `item['timestamp']`. You can do a direct comparison against the value.
2. The comparison implementation for a date time object is more expensive than a comparison for int.

2023-03-25 00:51 UTC, manasaV3 commented on backend/api/model.py
> +    return maintenance_timeline[-limit:]
We don't need the slicing here on the limit anymore as we only append the entries that are within the limit.

2023-04-13 04:28 UTC, klai95 commented
`(get_metrics_for_plugin('zarpaint', '3', False))`
`Response`
{'usage': {'timeline': [{'timestamp': 1672531200000, 'installs': 2}, {'timestamp': 1675209600000, 'installs': 8}, {'timestamp': 1677628800000, 'installs': 6}], 'stats': {'total_installs': 220, 'installs_in_last_30_days': 4}}, 'maintenance': {'timeline': [{'timestamp': 1672531200000, 'commits': 0}, {'timestamp': 1675209600000, 'commits': 0}, {'timestamp': 1677628800000, 'commits': 0}], 'stats': {'latest_commit_timestamp': 1668955796000, 'total_commits': 35}}}

`get_metrics_for_plugin('napari-bigfish', '3', False)`
`Response`
{'usage': {'timeline': [{'timestamp': 1672531200000, 'installs': 0}, {'timestamp': 1675209600000, 'installs': 0}, {'timestamp': 1677628800000, 'installs': 0}], 'stats': {'total_installs': 4, 'installs_in_last_30_days': 4}}, 'maintenance': {'timeline': [{'timestamp': 1672531200000, 'commits': 0}, {'timestamp': 1675209600000, 'commits': 0}, {'timestamp': 1677628800000, 'commits': 0}], 'stats': {'latest_commit_timestamp': None, 'total_commits': 0}}}

`get_metrics_for_plugin('zarpaint', '0', False)`
`Response`
{'usage': {'timeline': [], 'stats': {'total_installs': 220, 'installs_in_last_30_days': 4}}, 'maintenance': {'timeline': [], 'stats': {'latest_commit_timestamp': 1668955796000, 'total_commits': 35}}}

`get_metrics_for_plugin('zarpaint', 'foo', False)`
`Response`
{'usage': {'timeline': [], 'stats': {'total_installs': 220, 'installs_in_last_30_days': 4}}, 'maintenance': {'timeline': [], 'stats': {'latest_commit_timestamp': 1668955796000, 'total_commits': 35}}}

`get_metrics_for_plugin('zarpaint', '-5', False)`
`Response`
{'usage': {'timeline': [], 'stats': {'total_installs': 220, 'installs_in_last_30_days': 4}}, 'maintenance': {'timeline': [], 'stats': {'latest_commit_timestamp': 1668955796000, 'total_commits': 35}}}

2023-04-13 05:23 UTC, richaagarwal commented on backend/api/model.py
> +def _process_usage_timeline(plugin_df, limit):
Great idea renaming this one!

2023-04-13 05:25 UTC, richaagarwal commented on backend/api/model.py
> +    end_date = datetime(now.year, now.month - 1, 1) if now.month > 1 else datetime(now.year - 1, 12, 1)
I find the way `end_date` is calculated in line 434 a lot more readable. Any particular reason you didn't want to do it that way?

2023-04-13 17:37 UTC, klai95 commented on backend/api/model.py
> +    end_date = datetime(now.year, now.month - 1, 1) if now.month > 1 else datetime(now.year - 1, 12, 1)
The original intention was to define `start_date` and `end_date` as type `datetime.datetime`, so that we could directly compare `start_date <= item_date <= end_date` without any conversions, since the implementation on line 434 and line 435 are type `datetime.date`.

That being said, after some thinking, I do agree the way that `end_date` is written here is a bit more complex than it needs to be, so I have decided to follow the logic in `_process_usage_timeline` to generate `start_date` and `end_date`.

I have also the `__process_for_dates` method that returns `start_date, end_date, dates`, which can be used by both `_process_usage_timeline` and `_process_maintenance_timeline` to avoid code duplication.

I have locally tested the current implementation and it works as expected, in the same way outlined in https://github.com/chanzuckerberg/napari-hub/pull/960#issuecomment-1506326020

2023-04-14 00:36 UTC, richaagarwal commented on backend/api/model.py
> +    maintenance_dict = {item_datetime: item for item in commit_activity if
There's a lot going on here and it's hard to follow in a single line.  How about something similar to:
```
for commit in commit_activity:
    commit_date = ...
    if start_date <= commit_date <= end_date:
        add commit to list
```

2023-04-14 18:45 UTC, richaagarwal approved these changes

2023-04-14 19:04 UTC, kne42 reviewed
I like the function name updates since it makes them more self-explanatory!

2023-04-14 19:35 UTC, merged