No commit data shown on napari hub for hidden plugins
chanzuckerberg/napari-hub pull request #989
Opened 2023-04-10 01:44 UTC by klai95

`Problem`: Currently, there are plugins we are not showing commit data even though we have Snowflake data for them. The reason for this behavior is as follows: Since we only have access to repo values in `latest_commit` and `commit_activity` SQL queries, we created a dictionary that contains repo to plugin mappings, but such mappings are only available for public plugins, or in other words, plugins that exist in `index.json`, and this is the reason why hidden plugins (such as `napari-threedee`), which do not exist in `index.json`, did not have commit data.

`References`: Please check out https://www.napari-hub.org/plugins/napari-threedee and click on the `Activity` tab, and see the commits at https://github.com/napari-threedee/napari-threedee.

2023-04-10 03:05 UTC, klai95 commented
`Snowflake latest_commit data` for `napari-threedee`
<img width="1498" alt="Screenshot 2023-04-09 at 10 03 44 PM" src="https://user-images.githubuserconte
<img width="138" alt="Screenshot 2023-04-09 at 10 04 59 PM" src="https://user-images.githubusercontent.com/70177777/230817272-357917e7-aae5-40ad-8686-bf28ed81fcf0.png">
nt.com/70177777/230817147-3a3c822a-a1bc-40d0-8823-6d24dca159ae.png">

`Snowflake commit_activity data` for `napari-threedee`
<img width="1499" alt="Screenshot 2023-04-09 at 10 00 12 PM" src="https://user-images.githubusercontent.com/70177777/230816763-465819ba-1707-464b-a46a-ce28018ce041.png">
`commit_activity.json` for `napari-threedee`
<img width="763" alt="Screenshot 2023-04-09 at 10 01 07 PM" src="https://user-images.githubusercontent.com/70177777/230816871-3278f0d6-a8d4-4697-abb3-e5250975cb1b.png">

2023-04-10 03:29 UTC, klai95 commented
Here is the current list of hidden plugins. [The current implementation](https://github.com/chanzuckerberg/napari-hub/pull/989/files#diff-0ab08ad5c775cdda3530d5690e3f32dc4b670e91f86849f4d17260fda27196bcR516) adds commit data for all hidden plugins except for `PoseR-napari`. The reason is that `PoseR-napari` is the only plugin in which the repo name is not an exact match to its corresponding plugin name, as shown below.
<img width="1728" alt="Screenshot 2023-04-09 at 10 16 12 PM" src="https://user-images.githubusercontent.com/70177777/230818498-8267739f-3a49-44b9-a283-14076ff5d8df.png">
<img width="1498" alt="Screenshot 2023-04-09 at 10 21 09 PM" src="https://user-images.githubusercontent.com/70177777/230819029-ee3e06dd-037e-41ec-8f77-993c1d95d00c.png">

If we do want to include commit data for `PoseR-napari`, I see two potential approaches:
- we could do substring match, and since `PoserR` is a substring of `PoseR-napari`, we would be able to store its data. This approach is not very rigorous, as we may run into future cases where there are multiple substring matches, and therefore the approach may introduce false positives
- we could maintain a hard-coded dict that maps repos to plugins. If we were to go with this approach, `PoseR-napari` would be the only item in the dictionary currently, as all other plugins (public or hidden) would have commit data. This is also not an ideal solution.

What are your thoughts on this matter? @richaagarwal

2023-04-10 17:48 UTC, manasaV3 requested changes

2023-04-10 17:48 UTC, manasaV3 commented on backend/api/model.py
> +                plugin = repo_name
I believe we went over why this would not work in [here](https://github.com/chanzuckerberg/napari-hub/pull/939#discussion_r1159419991)

2023-04-10 18:22 UTC, klai95 commented on backend/api/model.py
> +                plugin = repo_name
That make sense to me. I have some confusion as to why we would use `get_excluded_plugins()` instead of `get_hidden_plugins()`. Take `napping` the plugin which has `disabled` visibility for example, it does not show up at all on https://www.napari-hub.org/plugins/napping. The same thing applies for https://www.napari-hub.org/plugins/napari-aphid, which is also a disabled plugin.

2023-04-10 18:36 UTC, manasaV3 commented on backend/api/model.py
> +                plugin = repo_name
It is more so to improve coverage for future extensibility.  
For example, if a plugin went from disabled to visible during the day, we would already have data for it if it exists in the snowflake. 
But, having the data from the workflow running the subsequent day would not be too bad. So, while I would recommend using excluded plugins, we should also be fine with using just the hidden plugins.

2023-04-10 18:39 UTC, klai95 commented on backend/api/model.py
> +                plugin = repo_name
Ok, I see what you're saying. I think using excluded plugins makes sense then. Thanks for the clarification

2023-04-10 18:57 UTC, klai95 commented on backend/api/model.py
> +                plugin = repo_name
Just to verify, this means that, for the non-hidden plugins in `excluded_plugins.json`, we would call `get_plugin` but we don't pass in the version since we don't have access to that value right?

2023-04-10 21:12 UTC, klai95 commented
Based on [Manasa's recommended approach](https://github.com/chanzuckerberg/napari-hub/pull/989#discussion_r1161943122), the PR now captures commit data for `PoseR-napari`, as well as any other plugins whose plugin names do not match their repo names. Furthermore, we are leveraging `get_excluded_plugins()` instead of `get_hidden_plugins()` to further increase the coverage. 


`latest_commit` for `PoseR-napari`
<img width="202" alt="Screenshot 2023-04-10 at 4 11 40 PM" src="https://user-images.githubusercontent.com/70177777/230999762-3101a992-43ac-48f6-bc93-544b5e7fbe40.png">
png">

`commit activity` for `PoseR-napari`
<img width="409" alt="Screenshot 2023-04-10 at 4 11 20 PM" src="https://user-images.githubusercontent.com/70177777/230999706-a67f95a9-007f-4d67-92e1-6efe453158a7.

2023-04-10 21:33 UTC, manasaV3 approved these changes
:shipit:

2023-04-10 21:33 UTC, manasaV3 commented on backend/api/model.py
> +    return repo_to_plugin_dict
Nit: We don't need to return it here as the caller method already has the dict available.

2023-04-10 22:49 UTC, merged

2023-04-10 23:19 UTC, richaagarwal commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
I believe this line will fail to retrieve plugin metadata: if no version is passed, and it is an excluded plugin that is not hidden, it won't be returned from `get_valid_plugins()` that `get_plugin` calls in order to retrieve the latest version.  

Were you able to test this before merging @klai95 ?

2023-04-10 23:21 UTC, richaagarwal commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
Thinking through this more, I don't think we'd have metadata for an excluded/non-hidden plugin in the first place, so we may not be able to include these in the activity fetch.

2023-04-10 23:56 UTC, klai95 commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
@richaagarwal Yeah, I did test this to ensure that the workflow produces the correct data and no error takes place. For the non-hidden plugins in `excluded_plugins.json`, excluded_plugin_obj is `{}`. `plugin_obj.get('code_repository')` in `_update_repo_to_plugin_dict` is `None`, and therefore those plugins are not added to repo_to_plugin_dict due to the `if code_repository` check in `_update_repo_to_plugin_dict`. As a result, `repo_to_plugin_dict` contains data for public and hidden plugins only. We can certainly only call `get_hidden_plugins()`, but the actual data in `repo_to_plugin_dict`  would be exactly the same and no errors are produced in either scenario.

2023-04-11 00:10 UTC, klai95 commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
If it makes sense, I could create a follow-up PR. As it stands, we wouldn't be able to increase coverage (https://github.com/chanzuckerberg/napari-hub/pull/989#discussion_r1161943122), since there is no data for the non-hidden plugins that are excluded.

2023-04-11 00:45 UTC, richaagarwal commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
Okay, just wanted to flag this so we're all on the same page. This block of code is a little complicated and potentially misleading since we're not, in practice, getting additional metadata from the excluded list. However, since we're going to clean this all up soon with the migration effort, I think it's fine to leave as is for now.

2023-04-11 00:48 UTC, klai95 commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
Sounds good, I will keep this in mind. I will also make the necessary changes in the current PR I am working on: https://github.com/chanzuckerberg/napari-hub/pull/939

2023-04-11 01:12 UTC, klai95 commented on backend/api/model.py
> +            excluded_plugin_obj = get_plugin(excluded_plugin_name, None)
Just going to put the snippet of code here so we can use it when we refactor:
```
hidden_plugins = _get_cache('cache/hidden-plugins.json')
for hidden_plugin_name, hidden_plugin_version in hidden_plugins.items():
  hidden_plugin_obj = get_plugin(hidden_plugin_name, hidden_plugin_version)
  repo_to_plugin_dict = _update_repo_to_plugin_dict(repo_to_plugin_dict, hidden_plugin_obj)